package parser;
import java_cup.runtime.*;
import java.util.Hashtable;

class Parser;

action code {:
    Hashtable table = new Hashtable();
:};

parser code {:
    public void syntax_error(Symbol s){
        System.out.println("Error en la linea "+ (s.left+1)+ " Columna "+ s.right+ ". Valor simbolo '"
        +s.value+"' . Simbolo n° "+s.sym+ " no reconocido." );
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.out.println("Error en la linea "+ (s.left+1)+ " Columna "+ s.right+ ". Valor simbolo '"
        +s.value+"' . Simbolo n° "+s.sym+ " no reconocido." );
    }
:};


terminal MAS, MENOS, MULT, DIV, PAR_ABRE, PAR_CIERRA, MENOS_UNARIO;
terminal String IDENTIFICADOR, ENTERO;

nonterminal String expression, expr;

precedence left MAS, MENOS;
precedence left MULT, DIV;
precedence left MENOS_UNARIO;

start with expression;

expression ::= expr:e {:
            System.out.println("REGLA 0: expression -> expr");
            System.out.printf("REGLA 0: expression -> %s%n%n", e);
            RESULT = e;
        :};

expr ::= expr:e1 MAS expr:e2 {:
            System.out.println("REGLA 1.1: expr -> expr MAS expr");
            System.out.printf("REGLA 1.1: expr -> %s MAS %s%n%n", e1, e2);
            RESULT = e1+"+"+e2;
        :};

expr ::= expr:e1 MENOS expr:e2 {:
            System.out.println("REGLA 1.2: expr -> expr MENOS expr");
            System.out.printf("REGLA 1.2: expr -> %s MENOS %s%n%n", e1, e2);
            RESULT = e1+"-"+e2;
        :};

expr ::= expr:e1 MULT expr:e2 {:
            System.out.println("REGLA 1.3: expr -> expr MULT expr");
            System.out.printf("REGLA 1.3: expr -> %s MULT %s%n%n", e1, e2);
            RESULT = e1+"*"+e2;
        :};

expr ::= expr:e1 DIV expr:e2 {:
            System.out.println("REGLA 1.4: expr -> expr DIV expr");
            System.out.printf("REGLA 1.4: expr -> %s DIV %s%n%n", e1, e2);
            RESULT = e1+"/"+e2;
        :};

expr ::= PAR_ABRE expr:e PAR_CIERRA {:
            System.out.println("REGLA 1.5: expr -> ( expr )");
            System.out.printf("REGLA 1.5: expr -> ( %s )%n%n", e);
            RESULT = "("+e+")";
        :};

expr ::= IDENTIFICADOR:id {:
            System.out.println("REGLA 1.6: expr -> IDENTIFICADOR");
            System.out.printf("REGLA 1.6: expr -> %s%n%n", id);
            RESULT = id;
        :};

expr ::= ENTERO:ent {:
            System.out.println("REGLA 1.7: expr -> ENTERO");
            System.out.printf("REGLA 1.7: expr -> %s%n%n", ent);
            RESULT = ent;
        :};

expr ::= MENOS expr:e {:
            System.out.println("REGLA 1.8: expr -> MENOS expr");
            System.out.printf("REGLA 1.8: expr -> - %s%n%n", e);
            RESULT = "-"+e;
        :} %prec MENOS_UNARIO;
