
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import java.util.Hashtable;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\072\000\002\002\004\000\002\002\005\000\002\006" +
    "\003\000\002\006\002\000\002\007\004\000\002\007\003" +
    "\000\002\010\005\000\002\010\010\000\002\011\005\000" +
    "\002\011\003\000\002\012\003\000\002\012\003\000\002" +
    "\012\003\000\002\012\003\000\002\003\004\000\002\003" +
    "\002\000\002\005\005\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\004\000\002\004\006\000" +
    "\002\004\003\000\002\004\003\000\002\004\005\000\002" +
    "\013\006\000\002\014\006\000\002\014\004\000\002\014" +
    "\002\000\002\015\005\000\002\016\005\000\002\017\005" +
    "\000\002\017\005\000\002\017\004\000\002\017\003\000" +
    "\002\020\005\000\002\020\005\000\002\020\005\000\002" +
    "\020\005\000\002\020\005\000\002\020\003\000\002\021" +
    "\005\000\002\021\005\000\002\021\003\000\002\022\005" +
    "\000\002\022\005\000\002\022\003\000\002\023\003\000" +
    "\002\023\003\000\002\023\003\000\002\023\003\000\002" +
    "\023\006\000\002\023\003\000\002\023\003\000\002\023" +
    "\003\000\002\023\003\000\002\023\005\000\002\023\004" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\146\000\016\015\006\016\010\017\014\020\007\021" +
    "\013\022\ufffe\001\002\000\004\002\150\001\002\000\004" +
    "\012\146\001\002\000\004\012\ufff7\001\002\000\004\012" +
    "\ufff4\001\002\000\004\012\ufff6\001\002\000\016\015\ufffc" +
    "\016\ufffc\017\ufffc\020\ufffc\021\ufffc\022\ufffc\001\002\000" +
    "\004\022\027\001\002\000\004\054\017\001\002\000\004" +
    "\012\ufff5\001\002\000\016\015\006\016\010\017\014\020" +
    "\007\021\013\022\uffff\001\002\000\016\015\ufffd\016\ufffd" +
    "\017\ufffd\020\ufffd\021\ufffd\022\ufffd\001\002\000\004\005" +
    "\020\001\002\000\004\055\021\001\002\000\004\012\022" +
    "\001\002\000\004\004\023\001\002\000\020\013\ufff8\015" +
    "\ufff8\016\ufff8\017\ufff8\020\ufff8\021\ufff8\022\ufff8\001\002" +
    "\000\020\013\025\015\ufffa\016\ufffa\017\ufffa\020\ufffa\021" +
    "\ufffa\022\ufffa\001\002\000\004\004\026\001\002\000\020" +
    "\013\ufff9\015\ufff9\016\ufff9\017\ufff9\020\ufff9\021\ufff9\022" +
    "\ufff9\001\002\000\022\002\ufff2\004\ufff2\023\ufff2\026\ufff2" +
    "\027\ufff2\032\ufff2\033\ufff2\034\ufff2\001\002\000\022\002" +
    "\000\004\037\023\036\026\031\027\033\032\040\033\043" +
    "\034\041\001\002\000\030\004\054\005\047\006\062\007" +
    "\052\010\050\036\046\043\057\052\064\060\061\061\060" +
    "\062\063\001\002\000\024\002\uffef\004\uffef\023\uffef\026" +
    "\uffef\027\uffef\032\uffef\033\uffef\034\uffef\057\uffef\001\002" +
    "\000\030\004\054\005\047\006\062\007\052\010\050\036" +
    "\046\043\057\052\064\060\061\061\060\062\063\001\002" +
    "\000\024\002\ufff3\004\ufff3\023\ufff3\026\ufff3\027\ufff3\032" +
    "\ufff3\033\ufff3\034\ufff3\057\ufff3\001\002\000\024\002\uffee" +
    "\004\uffee\023\uffee\026\uffee\027\uffee\032\uffee\033\uffee\034" +
    "\uffee\057\uffee\001\002\000\030\004\054\005\047\006\062" +
    "\007\052\010\050\036\046\043\057\052\064\060\061\061" +
    "\060\062\063\001\002\000\004\044\124\001\002\000\030" +
    "\004\054\005\047\006\062\007\052\010\050\036\046\043" +
    "\057\052\044\060\061\061\060\062\063\001\002\000\024" +
    "\002\uffea\004\uffea\023\uffea\026\uffea\027\uffea\032\uffea\033" +
    "\uffea\034\uffea\057\uffea\001\002\000\024\002\ufff0\004\ufff0" +
    "\023\ufff0\026\ufff0\027\ufff0\032\ufff0\033\ufff0\034\ufff0\057" +
    "\ufff0\001\002\000\024\002\uffeb\004\uffeb\023\uffeb\026\uffeb" +
    "\027\uffeb\032\uffeb\033\uffeb\034\uffeb\057\uffeb\001\002\000" +
    "\032\004\054\005\047\006\062\007\052\010\050\011\122" +
    "\036\046\043\057\052\064\060\061\061\060\062\063\001" +
    "\002\000\030\002\uffed\004\uffed\023\uffed\026\uffed\027\uffed" +
    "\032\uffed\033\uffed\034\uffed\041\070\042\071\057\uffed\001" +
    "\002\000\026\004\054\005\047\006\062\007\052\010\050" +
    "\036\046\052\064\060\061\061\060\062\063\001\002\000" +
    "\060\002\uffd2\004\uffd2\023\uffd2\026\uffd2\027\uffd2\032\uffd2" +
    "\033\uffd2\034\uffd2\035\uffd2\036\uffd2\037\uffd2\040\uffd2\041" +
    "\uffd2\042\uffd2\045\uffd2\046\uffd2\047\uffd2\050\uffd2\051\uffd2" +
    "\053\uffd2\055\uffd2\056\uffd2\057\uffd2\001\002\000\060\002" +
    "\uffd0\004\uffd0\023\uffd0\026\uffd0\027\uffd0\032\uffd0\033\uffd0" +
    "\034\uffd0\035\uffd0\036\uffd0\037\uffd0\040\uffd0\041\uffd0\042" +
    "\uffd0\045\uffd0\046\uffd0\047\uffd0\050\uffd0\051\uffd0\053\uffd0" +
    "\055\uffd0\056\uffd0\057\uffd0\001\002\000\060\002\uffd6\004" +
    "\uffd6\023\uffd6\026\uffd6\027\uffd6\032\uffd6\033\uffd6\034\uffd6" +
    "\035\uffd6\036\uffd6\037\102\040\103\041\uffd6\042\uffd6\045" +
    "\uffd6\046\uffd6\047\uffd6\050\uffd6\051\uffd6\053\uffd6\055\uffd6" +
    "\056\uffd6\057\uffd6\001\002\000\060\002\uffcd\004\uffcd\023" +
    "\uffcd\026\uffcd\027\uffcd\032\uffcd\033\uffcd\034\uffcd\035\uffcd" +
    "\036\uffcd\037\uffcd\040\uffcd\041\uffcd\042\uffcd\045\uffcd\046" +
    "\uffcd\047\uffcd\050\uffcd\051\uffcd\053\uffcd\055\uffcd\056\uffcd" +
    "\057\uffcd\001\002\000\052\002\uffd9\004\uffd9\023\uffd9\026" +
    "\uffd9\027\uffd9\032\uffd9\033\uffd9\034\uffd9\035\076\036\077" +
    "\041\uffd9\042\uffd9\045\112\046\113\047\111\050\110\051" +
    "\107\053\uffd9\056\uffd9\057\uffd9\001\002\000\062\002\uffcf" +
    "\004\uffcf\023\uffcf\026\uffcf\027\uffcf\032\uffcf\033\uffcf\034" +
    "\uffcf\035\uffcf\036\uffcf\037\uffcf\040\uffcf\041\uffcf\042\uffcf" +
    "\045\uffcf\046\uffcf\047\uffcf\050\uffcf\051\uffcf\053\uffcf\054" +
    "\074\055\uffcf\056\uffcf\057\uffcf\001\002\000\060\002\uffd3" +
    "\004\uffd3\023\uffd3\026\uffd3\027\uffd3\032\uffd3\033\uffd3\034" +
    "\uffd3\035\uffd3\036\uffd3\037\uffd3\040\uffd3\041\uffd3\042\uffd3" +
    "\045\uffd3\046\uffd3\047\uffd3\050\uffd3\051\uffd3\053\uffd3\055" +
    "\uffd3\056\uffd3\057\uffd3\001\002\000\034\002\uffdf\004\uffdf" +
    "\023\uffdf\026\uffdf\027\uffdf\032\uffdf\033\uffdf\034\uffdf\041" +
    "\uffdf\042\uffdf\053\uffdf\056\uffdf\057\uffdf\001\002\000\026" +
    "\004\054\005\047\006\062\007\052\010\050\036\046\052" +
    "\064\060\061\061\060\062\063\001\002\000\060\002\uffcb" +
    "\004\uffcb\023\uffcb\026\uffcb\027\uffcb\032\uffcb\033\uffcb\034" +
    "\uffcb\035\uffcb\036\uffcb\037\uffcb\040\uffcb\041\uffcb\042\uffcb" +
    "\045\uffcb\046\uffcb\047\uffcb\050\uffcb\051\uffcb\053\uffcb\055" +
    "\uffcb\056\uffcb\057\uffcb\001\002\000\060\002\uffcc\004\uffcc" +
    "\023\uffcc\026\uffcc\027\uffcc\032\uffcc\033\uffcc\034\uffcc\035" +
    "\uffcc\036\uffcc\037\uffcc\040\uffcc\041\uffcc\042\uffcc\045\uffcc" +
    "\046\uffcc\047\uffcc\050\uffcc\051\uffcc\053\uffcc\055\uffcc\056" +
    "\uffcc\057\uffcc\001\002\000\060\002\uffd1\004\uffd1\023\uffd1" +
    "\026\uffd1\027\uffd1\032\uffd1\033\uffd1\034\uffd1\035\uffd1\036" +
    "\uffd1\037\uffd1\040\uffd1\041\uffd1\042\uffd1\045\uffd1\046\uffd1" +
    "\047\uffd1\050\uffd1\051\uffd1\053\uffd1\055\uffd1\056\uffd1\057" +
    "\uffd1\001\002\000\060\002\uffca\004\uffca\023\uffca\026\uffca" +
    "\027\uffca\032\uffca\033\uffca\034\uffca\035\uffca\036\uffca\037" +
    "\uffca\040\uffca\041\uffca\042\uffca\045\uffca\046\uffca\047\uffca" +
    "\050\uffca\051\uffca\053\uffca\055\uffca\056\uffca\057\uffca\001" +
    "\002\000\030\004\054\005\047\006\062\007\052\010\050" +
    "\036\046\043\057\052\064\060\061\061\060\062\063\001" +
    "\002\000\034\002\uffe0\004\uffe0\023\uffe0\026\uffe0\027\uffe0" +
    "\032\uffe0\033\uffe0\034\uffe0\041\uffe0\042\uffe0\053\uffe0\056" +
    "\uffe0\057\uffe0\001\002\000\010\041\070\042\071\053\067" +
    "\001\002\000\060\002\uffc9\004\uffc9\023\uffc9\026\uffc9\027" +
    "\uffc9\032\uffc9\033\uffc9\034\uffc9\035\uffc9\036\uffc9\037\uffc9" +
    "\040\uffc9\041\uffc9\042\uffc9\045\uffc9\046\uffc9\047\uffc9\050" +
    "\uffc9\051\uffc9\053\uffc9\055\uffc9\056\uffc9\057\uffc9\001\002" +
    "\000\026\004\054\005\047\006\062\007\052\010\050\036" +
    "\046\052\064\060\061\061\060\062\063\001\002\000\026" +
    "\004\054\005\047\006\062\007\052\010\050\036\046\052" +
    "\064\060\061\061\060\062\063\001\002\000\034\002\uffe2" +
    "\004\uffe2\023\uffe2\026\uffe2\027\uffe2\032\uffe2\033\uffe2\034" +
    "\uffe2\041\uffe2\042\uffe2\053\uffe2\056\uffe2\057\uffe2\001\002" +
    "\000\034\002\uffe1\004\uffe1\023\uffe1\026\uffe1\027\uffe1\032" +
    "\uffe1\033\uffe1\034\uffe1\041\uffe1\042\uffe1\053\uffe1\056\uffe1" +
    "\057\uffe1\001\002\000\026\004\054\005\047\006\062\007" +
    "\052\010\050\036\046\052\064\060\061\061\060\062\063" +
    "\001\002\000\010\035\076\036\077\055\100\001\002\000" +
    "\026\004\054\005\047\006\062\007\052\010\050\036\046" +
    "\052\064\060\061\061\060\062\063\001\002\000\026\004" +
    "\054\005\047\006\062\007\052\010\050\036\046\052\064" +
    "\060\061\061\060\062\063\001\002\000\060\002\uffce\004" +
    "\uffce\023\uffce\026\uffce\027\uffce\032\uffce\033\uffce\034\uffce" +
    "\035\uffce\036\uffce\037\uffce\040\uffce\041\uffce\042\uffce\045" +
    "\uffce\046\uffce\047\uffce\050\uffce\051\uffce\053\uffce\055\uffce" +
    "\056\uffce\057\uffce\001\002\000\060\002\uffd7\004\uffd7\023" +
    "\uffd7\026\uffd7\027\uffd7\032\uffd7\033\uffd7\034\uffd7\035\uffd7" +
    "\036\uffd7\037\102\040\103\041\uffd7\042\uffd7\045\uffd7\046" +
    "\uffd7\047\uffd7\050\uffd7\051\uffd7\053\uffd7\055\uffd7\056\uffd7" +
    "\057\uffd7\001\002\000\026\004\054\005\047\006\062\007" +
    "\052\010\050\036\046\052\064\060\061\061\060\062\063" +
    "\001\002\000\026\004\054\005\047\006\062\007\052\010" +
    "\050\036\046\052\064\060\061\061\060\062\063\001\002" +
    "\000\060\002\uffd4\004\uffd4\023\uffd4\026\uffd4\027\uffd4\032" +
    "\uffd4\033\uffd4\034\uffd4\035\uffd4\036\uffd4\037\uffd4\040\uffd4" +
    "\041\uffd4\042\uffd4\045\uffd4\046\uffd4\047\uffd4\050\uffd4\051" +
    "\uffd4\053\uffd4\055\uffd4\056\uffd4\057\uffd4\001\002\000\060" +
    "\002\uffd5\004\uffd5\023\uffd5\026\uffd5\027\uffd5\032\uffd5\033" +
    "\uffd5\034\uffd5\035\uffd5\036\uffd5\037\uffd5\040\uffd5\041\uffd5" +
    "\042\uffd5\045\uffd5\046\uffd5\047\uffd5\050\uffd5\051\uffd5\053" +
    "\uffd5\055\uffd5\056\uffd5\057\uffd5\001\002\000\060\002\uffd8" +
    "\004\uffd8\023\uffd8\026\uffd8\027\uffd8\032\uffd8\033\uffd8\034" +
    "\uffd8\035\uffd8\036\uffd8\037\102\040\103\041\uffd8\042\uffd8" +
    "\045\uffd8\046\uffd8\047\uffd8\050\uffd8\051\uffd8\053\uffd8\055" +
    "\uffd8\056\uffd8\057\uffd8\001\002\000\026\004\054\005\047" +
    "\006\062\007\052\010\050\036\046\052\064\060\061\061" +
    "\060\062\063\001\002\000\026\004\054\005\047\006\062" +
    "\007\052\010\050\036\046\052\064\060\061\061\060\062" +
    "\063\001\002\000\026\004\054\005\047\006\062\007\052" +
    "\010\050\036\046\052\064\060\061\061\060\062\063\001" +
    "\002\000\026\004\054\005\047\006\062\007\052\010\050" +
    "\036\046\052\064\060\061\061\060\062\063\001\002\000" +
    "\026\004\054\005\047\006\062\007\052\010\050\036\046" +
    "\052\064\060\061\061\060\062\063\001\002\000\040\002" +
    "\uffdd\004\uffdd\023\uffdd\026\uffdd\027\uffdd\032\uffdd\033\uffdd" +
    "\034\uffdd\035\076\036\077\041\uffdd\042\uffdd\053\uffdd\056" +
    "\uffdd\057\uffdd\001\002\000\040\002\uffde\004\uffde\023\uffde" +
    "\026\uffde\027\uffde\032\uffde\033\uffde\034\uffde\035\076\036" +
    "\077\041\uffde\042\uffde\053\uffde\056\uffde\057\uffde\001\002" +
    "\000\040\002\uffdc\004\uffdc\023\uffdc\026\uffdc\027\uffdc\032" +
    "\uffdc\033\uffdc\034\uffdc\035\076\036\077\041\uffdc\042\uffdc" +
    "\053\uffdc\056\uffdc\057\uffdc\001\002\000\040\002\uffdb\004" +
    "\uffdb\023\uffdb\026\uffdb\027\uffdb\032\uffdb\033\uffdb\034\uffdb" +
    "\035\076\036\077\041\uffdb\042\uffdb\053\uffdb\056\uffdb\057" +
    "\uffdb\001\002\000\040\002\uffda\004\uffda\023\uffda\026\uffda" +
    "\027\uffda\032\uffda\033\uffda\034\uffda\035\076\036\077\041" +
    "\uffda\042\uffda\053\uffda\056\uffda\057\uffda\001\002\000\060" +
    "\002\uffc8\004\uffc8\023\uffc8\026\uffc8\027\uffc8\032\uffc8\033" +
    "\uffc8\034\uffc8\035\uffc8\036\uffc8\037\uffc8\040\uffc8\041\uffc8" +
    "\042\uffc8\045\uffc8\046\uffc8\047\uffc8\050\uffc8\051\uffc8\053" +
    "\uffc8\055\uffc8\056\uffc8\057\uffc8\001\002\000\004\053\123" +
    "\001\002\000\024\002\uffec\004\uffec\023\uffec\026\uffec\027" +
    "\uffec\032\uffec\033\uffec\034\uffec\057\uffec\001\002\000\030" +
    "\004\054\005\047\006\062\007\052\010\050\036\046\043" +
    "\057\052\064\060\061\061\060\062\063\001\002\000\030" +
    "\002\uffe9\004\uffe9\023\uffe9\026\uffe9\027\uffe9\032\uffe9\033" +
    "\uffe9\034\uffe9\041\070\042\071\057\uffe9\001\002\000\010" +
    "\041\070\042\071\056\130\001\002\000\030\002\uffe5\004" +
    "\uffe5\023\uffe5\024\133\025\135\026\uffe5\027\uffe5\032\uffe5" +
    "\033\uffe5\034\uffe5\057\uffe5\001\002\000\022\004\ufff2\023" +
    "\ufff2\026\ufff2\027\ufff2\032\ufff2\033\ufff2\034\ufff2\057\ufff2" +
    "\001\002\000\022\004\037\023\036\026\031\027\033\032" +
    "\040\033\043\034\041\057\132\001\002\000\030\002\ufff1" +
    "\004\ufff1\023\ufff1\024\ufff1\025\ufff1\026\ufff1\027\ufff1\032" +
    "\ufff1\033\ufff1\034\ufff1\057\ufff1\001\002\000\004\056\130" +
    "\001\002\000\024\002\uffe8\004\uffe8\023\uffe8\026\uffe8\027" +
    "\uffe8\032\uffe8\033\uffe8\034\uffe8\057\uffe8\001\002\000\030" +
    "\004\054\005\047\006\062\007\052\010\050\036\046\043" +
    "\057\052\064\060\061\061\060\062\063\001\002\000\010" +
    "\041\070\042\071\056\130\001\002\000\030\002\uffe5\004" +
    "\uffe5\023\uffe5\024\133\025\135\026\uffe5\027\uffe5\032\uffe5" +
    "\033\uffe5\034\uffe5\057\uffe5\001\002\000\024\002\uffe7\004" +
    "\uffe7\023\uffe7\026\uffe7\027\uffe7\032\uffe7\033\uffe7\034\uffe7" +
    "\057\uffe7\001\002\000\024\002\uffe6\004\uffe6\023\uffe6\026" +
    "\uffe6\027\uffe6\032\uffe6\033\uffe6\034\uffe6\057\uffe6\001\002" +
    "\000\010\041\070\042\071\056\130\001\002\000\024\002" +
    "\uffe3\004\uffe3\023\uffe3\026\uffe3\027\uffe3\032\uffe3\033\uffe3" +
    "\034\uffe3\057\uffe3\001\002\000\010\041\070\042\071\056" +
    "\130\001\002\000\024\002\uffe4\004\uffe4\023\uffe4\026\uffe4" +
    "\027\uffe4\032\uffe4\033\uffe4\034\uffe4\057\uffe4\001\002\000" +
    "\004\004\023\001\002\000\020\013\025\015\ufffb\016\ufffb" +
    "\017\ufffb\020\ufffb\021\ufffb\022\ufffb\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\146\000\014\002\003\006\011\007\014\010\010\012" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\010\015\012\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\027\001\001" +
    "\000\012\004\033\013\041\015\031\016\034\001\001\000" +
    "\014\017\143\020\055\021\052\022\050\023\054\001\001" +
    "\000\002\001\001\000\014\017\141\020\055\021\052\022" +
    "\050\023\054\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\017\125\020\055\021\052\022\050\023\054\001" +
    "\001\000\002\001\001\000\014\017\044\020\055\021\052" +
    "\022\050\023\054\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\017\065\020\055\021\052" +
    "\022\050\023\054\001\001\000\002\001\001\000\004\023" +
    "\120\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\020\064" +
    "\021\052\022\050\023\054\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\017\065\020\055\021\052\022\050\023\054\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\020\072\021\052\022\050\023\054\001\001\000\012\020" +
    "\071\021\052\022\050\023\054\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\021\074\022\050\023\054\001" +
    "\001\000\002\001\001\000\006\022\105\023\054\001\001" +
    "\000\006\022\100\023\054\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\023\104\001\001\000\004\023\103" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\021\117\022\050\023\054\001\001\000\010" +
    "\021\116\022\050\023\054\001\001\000\010\021\115\022" +
    "\050\023\054\001\001\000\010\021\114\022\050\023\054" +
    "\001\001\000\010\021\113\022\050\023\054\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\017\124\020\055\021\052" +
    "\022\050\023\054\001\001\000\002\001\001\000\004\005" +
    "\126\001\001\000\004\014\133\001\001\000\004\003\130" +
    "\001\001\000\012\004\033\013\041\015\031\016\034\001" +
    "\001\000\002\001\001\000\004\005\140\001\001\000\002" +
    "\001\001\000\014\017\135\020\055\021\052\022\050\023" +
    "\054\001\001\000\004\005\136\001\001\000\004\014\137" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\142\001\001\000\002\001\001\000\004\005\144\001\001" +
    "\000\002\001\001\000\004\011\146\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public SymbolTable tablaSimbolos = new SymbolTable();

    public void syntax_error(Symbol s){
        System.out.println("Error en la linea "+ (s.left+1)+ " Columna "+ s.right+ ". Valor simbolo '"
        +s.value+"' . Simbolo n° "+s.sym+ " no reconocido." );
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.out.println("Error en la linea "+ (s.left+1)+ " Columna "+ s.right+ ". Valor simbolo '"
        +s.value+"' . Simbolo n° "+s.sym+ " no reconocido." );
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {


    Hashtable table = new Hashtable();

  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_variables PROGRAM lista_sentencias 
            {
              String RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 0: programa -> PROGRAM lista_sentencias");
    System.out.printf("REGLA 0: programa -> %s%n%n", l);
    RESULT = l;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_variables ::= lista_de_lineas 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_variables",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_variables ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_variables",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_de_lineas ::= lista_de_lineas variable 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_de_lineas",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_de_lineas ::= variable 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_de_lineas",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // variable ::= tipo_datos DOS_PUNTOS lista_de_variable 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int nombresleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nombresright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<String> nombres = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
for (String id : nombres) {
        if (tablaSimbolos.exists(id)) {
            System.err.println("Error: Variable '" + id + "' ya declarada.");
        } else {
            tablaSimbolos.add(t, id, t, null, null);
            System.out.println("Declarado: " + id + " de tipo " + t);
        }
    }

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // variable ::= TYPE_ARRAY CORCH_A ENTERO CORCH_C DOS_PUNTOS lista_de_variable 
            {
              Object RESULT =null;
		int nombresleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nombresright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<String> nombres = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
String tipoEspecial = "FLOAT_ARRAY";
    for (String id : nombres) {
        if (tablaSimbolos.exists(id)) {
            System.err.println("Error: Variable '" + id + "' ya declarada.");
        } else {
            tablaSimbolos.add(tipoEspecial, id, null, null, null);
            System.out.println("Declarado: " + id + " de tipo " + tipoEspecial);
        }
    }

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // lista_de_variable ::= lista_de_variable COMA ID 
            {
              ArrayList<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<String> list = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
      list.add(e);
      RESULT = list;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_de_variable",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_de_variable ::= ID 
            {
              ArrayList<String> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList<String> lista = new ArrayList<>();
        lista.add(n);
        RESULT = lista;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_de_variable",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // tipo_datos ::= TYPE_INT 
            {
              String RESULT =null;
		 RESULT = "INT";  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_datos",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo_datos ::= TYPE_FLOAT 
            {
              String RESULT =null;
		 RESULT = "FLOAT";   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_datos",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // tipo_datos ::= TYPE_BOOL 
            {
              String RESULT =null;
		 RESULT = "BOOLEAN"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_datos",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // tipo_datos ::= TYPE_STR 
            {
              String RESULT =null;
		 RESULT = "STRING";  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_datos",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // lista_sentencias ::= lista_sentencias sentencia 
            {
              String RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 1.1: lista_sentencias -> lista_sentencias sentencia");
    System.out.printf("REGLA 1.1: lista_sentencias -> %s %s%n%n", l, s);
    RESULT = l + "\n" + s;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_sentencias ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // bloque ::= INDENT lista_sentencias DEDENT 
            {
              String RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    System.out.println("REGLA 8: bloque -> INDENT lista_sentencias DEDENT");
    System.out.printf("REGLA 8: bloque -> %s%n%n", l);
    RESULT = l;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= sentencia_if 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 3.1: sentencia -> sentencia_if");
    System.out.printf("REGLA 3.1: sentencia -> %s%n%n", s);
    RESULT = s;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= sentencia_while 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 3.2: sentencia -> sentencia_while");
    System.out.printf("REGLA 3.2: sentencia -> %s%n%n", s);
    RESULT = s;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= sentencia_alt 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 3.3: sentencia -> sentencia_alt");
    System.out.printf("REGLA 3.3: sentencia -> %s%n%n", s);
    RESULT = s;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= PRINT expr_logica 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 3.4: sentencia -> PRINT expresion");
    System.out.printf("REGLA 3.4: sentencia -> %s%n%n", e);
    RESULT = "print " + e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= PRINT PAREN_A STRING PAREN_C 
            {
              String RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        String contenido = str.replace("\"", "");

        // Según tu formato: ID (null o autogenerado), Tipo (CTE_STR), Valor (contenido)
        tablaSimbolos.add("CTE_STR", "-", "STRING", contenido, null);

        System.out.println("REGLA: PRINT -> cadena constante: " + contenido);
        RESULT = "print(" + str + ");";


              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= BREAK 
            {
              String RESULT =null;
		
    System.out.println("REGLA 3.5: sentencia -> BREAK");
    System.out.printf("REGLA 3.5: sentencia -> break%n%n");
    RESULT = "break";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= CONTINUE 
            {
              String RESULT =null;
		
    System.out.println("REGLA 3.6: sentencia -> CONTINUE");
    System.out.printf("REGLA 3.6: sentencia -> continue%n%n");
    RESULT = "continue";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sentencia ::= ID IGUAL expr_logica 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 3.7: sentencia -> ID = expresion");
    System.out.printf("REGLA 3.7: sentencia -> %s = %s%n%n", id, e);
    RESULT = "asignacion " + id;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sentencia_if ::= IF expr_logica bloque sentencia_elif 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int s_elifleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int s_elifright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s_elif = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 4: sentencia_if -> IF expresion bloque sentencia_elif");
    System.out.printf("REGLA 4: if %s then %s %s%n%n", e, b, s_elif);
    RESULT = "if";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia_elif ::= ELIF expr_logica bloque sentencia_elif 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 5.1: sentencia_elif -> ELIF expresion bloque sentencia_elif");
    System.out.printf("REGLA 5.1: elif %s then %s %s%n%n", e, b, s);
    RESULT = "elif";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_elif",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia_elif ::= ELSE bloque 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 5.2: sentencia_elif -> ELSE bloque");
    System.out.printf("REGLA 5.2: else %s%n%n", b);
    RESULT = "else";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_elif",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia_elif ::= 
            {
              String RESULT =null;
		
    System.out.println("REGLA 5.3: sentencia_elif -> epsilon");
    RESULT = "";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_elif",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia_while ::= WHILE expr_logica bloque 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 6: sentencia_while -> WHILE expresion bloque");
    System.out.printf("REGLA 6: while %s do %s%n%n", e, b);
    RESULT = "while";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_while",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia_alt ::= ALT_WHILE expr_logica bloque 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 7: sentencia_alt -> ALT_WHILE expresion bloque");
    System.out.printf("REGLA 7: alt_while %s do %s%n%n", e, b);
    RESULT = "alt while";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_alt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr_logica ::= expr_logica OR expr_relacional 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 10.1: expr_logica -> expr_logica OR expr_relacional");
    System.out.printf("REGLA 10.1: expr_logica -> %s OR %s%n%n", e1, e2);
    RESULT = e1 + " OR " + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_logica",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr_logica ::= expr_logica AND expr_relacional 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 10.2: expr_logica -> expr_logica AND expr_relacional");
    System.out.printf("REGLA 10.2: expr_logica -> %s AND %s%n%n", e1, e2);
    RESULT = e1 + " AND " + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_logica",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr_logica ::= NOT expr_relacional 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 10.3: expr_logica -> NOT expr_relacional");
    System.out.printf("REGLA 10.3: expr_logica -> NOT %s%n%n", e);
    RESULT = "NOT " + e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_logica",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr_logica ::= expr_relacional 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 10.4: expr_logica -> expr_relacional");
    System.out.printf("REGLA 10.4: expr_logica -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_logica",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr_relacional ::= expr_arit IGUALDAD expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 11.1: expr_relacional -> expr_arit IGUALDAD expr_arit");
    System.out.printf("REGLA 11.1: expr_relacional -> %s == %s%n%n", e1, e2);
    RESULT = e1 + " == " + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr_relacional ::= expr_arit MAYOR expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 11.2: expr_relacional -> expr_arit MAYOR expr_arit");
    System.out.printf("REGLA 11.2: expr_relacional -> %s > %s%n%n", e1, e2);
    RESULT = e1 + " > " + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr_relacional ::= expr_arit MENOR expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 11.3: expr_relacional -> expr_arit MENOR expr_arit");
    System.out.printf("REGLA 11.3: expr_relacional -> %s < %s%n%n", e1, e2);
    RESULT = e1 + " < " + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr_relacional ::= expr_arit MAYORIGUAL expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 11.4: expr_relacional -> expr_arit MAYORIGUAL expr_arit");
    System.out.printf("REGLA 11.4: expr_relacional -> %s >= %s%n%n", e1, e2);
    RESULT = e1 + " >= " + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr_relacional ::= expr_arit MENORIGUAL expr_arit 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 11.5: expr_relacional -> expr_arit MENORIGUAL expr_arit");
    System.out.printf("REGLA 11.5: expr_relacional -> %s <= %s%n%n", e1, e2);
    RESULT = e1 + " <= " + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr_relacional ::= expr_arit 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 11.6: expr_relacional -> expr_arit");
    System.out.printf("REGLA 11.6: expr_relacional -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr_arit ::= expr_arit OP_SUMA termino 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 12.1: expr_arit -> expr_arit OP_SUMA termino");
    System.out.printf("REGLA 12.1: expr_arit -> %s + %s%n%n", e1, e2);
    RESULT = e1 + "+" + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr_arit ::= expr_arit OP_RESTA termino 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 12.2: expr_arit -> expr_arit OP_RESTA termino");
    System.out.printf("REGLA 12.2: expr_arit -> %s - %s%n%n", e1, e2);
    RESULT = e1 + "-" + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr_arit ::= termino 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 12.3: expr_arit -> termino");
    System.out.printf("REGLA 12.3: expr_arit -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // termino ::= termino OP_MULTI factor 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 13.1: termino -> termino OP_MULTI factor");
    System.out.printf("REGLA 13.1: termino -> %s * %s%n%n", e1, e2);
    RESULT = e1 + "*" + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // termino ::= termino OP_DIV factor 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 13.2: termino -> termino OP_DIV factor");
    System.out.printf("REGLA 13.2: termino -> %s / %s%n%n", e1, e2);
    RESULT = e1 + "/" + e2;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // termino ::= factor 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 13.3: termino -> factor");
    System.out.printf("REGLA 13.3: termino -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // factor ::= ENTERO 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.1: factor -> ENTERO");
    System.out.printf("REGLA 14.1: factor -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // factor ::= FLOAT 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.2: factor -> FLOAT");
    System.out.printf("REGLA 14.2: factor -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // factor ::= BOOLEAN 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.3: factor -> BOOLEAN");
    System.out.printf("REGLA 14.3: factor -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // factor ::= ID 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.4: factor -> ID");
    System.out.printf("REGLA 14.4: factor -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // factor ::= ID CORCH_A expr_arit CORCH_C 
            {
              String RESULT =null;
		
    System.out.println("REGLA 14.8: factor -> ID");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // factor ::= FLOAT_ARRAY 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.5: factor -> FLOAT_ARRAY");
    System.out.printf("REGLA 14.5: factor -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // factor ::= READ_INT 
            {
              String RESULT =null;
		
    System.out.println("REGLA 14.5: factor -> READ_INT()");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // factor ::= READ_FLOAT 
            {
              String RESULT =null;
		
    System.out.println("REGLA 14.5: factor -> READ_FLOAT()");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // factor ::= READ_BOOL 
            {
              String RESULT =null;
		
    System.out.println("REGLA 14.5: factor -> READ_FLOAT()");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= PAREN_A expr_logica PAREN_C 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    System.out.println("REGLA 14.6: factor -> PAREN_A expresion PAREN_C");
    System.out.printf("REGLA 14.6: factor -> (%s)%n%n", e);
    RESULT = "(" + e + ")";

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= OP_RESTA factor 
            {
              String RESULT =null;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.X: factor -> - factor (unario)");
    System.out.printf("REGLA 14.X: factor -> -%s%n%n", y);
    RESULT = "-" + y;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
