
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int TYPE_ARRAY = 14;
  public static final int UMINUS = 10;
  public static final int ENTERO = 3;
  public static final int DOS_PUNTOS = 8;
  public static final int CONTINUE = 23;
  public static final int OP_MULTI = 27;
  public static final int OP_DIV = 28;
  public static final int MENORIGUAL = 37;
  public static final int NOT = 31;
  public static final int AND = 29;
  public static final int IGUAL = 32;
  public static final int IGUALDAD = 33;
  public static final int OR = 30;
  public static final int TYPE_INT = 11;
  public static final int IF = 16;
  public static final int ID = 2;
  public static final int MAYORIGUAL = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int READ_FLOAT = 46;
  public static final int error = 1;
  public static final int PROGRAM = 15;
  public static final int COMA = 9;
  public static final int FLOAT_ARRAY = 5;
  public static final int MENOR = 35;
  public static final int OP_RESTA = 26;
  public static final int BREAK = 22;
  public static final int DESIGUAL = 44;
  public static final int TYPE_FLOAT = 12;
  public static final int ALT_WHILE = 20;
  public static final int MAYOR = 34;
  public static final int READ_INT = 45;
  public static final int ELSE = 17;
  public static final int WHILE = 19;
  public static final int DEDENT = 43;
  public static final int FLOAT = 4;
  public static final int STRING = 7;
  public static final int PAREN_C = 39;
  public static final int PAREN_A = 38;
  public static final int OP_SUMA = 25;
  public static final int INDENT = 42;
  public static final int TYPE_BOOL = 13;
  public static final int READ_BOOL = 47;
  public static final int CORCH_C = 41;
  public static final int CORCH_A = 40;
  public static final int ELIF = 18;
  public static final int VALOR_MAS_CERCANO = 24;
  public static final int PRINT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "FLOAT",
  "FLOAT_ARRAY",
  "BOOLEAN",
  "STRING",
  "DOS_PUNTOS",
  "COMA",
  "UMINUS",
  "TYPE_INT",
  "TYPE_FLOAT",
  "TYPE_BOOL",
  "TYPE_ARRAY",
  "PROGRAM",
  "IF",
  "ELSE",
  "ELIF",
  "WHILE",
  "ALT_WHILE",
  "PRINT",
  "BREAK",
  "CONTINUE",
  "VALOR_MAS_CERCANO",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULTI",
  "OP_DIV",
  "AND",
  "OR",
  "NOT",
  "IGUAL",
  "IGUALDAD",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "PAREN_A",
  "PAREN_C",
  "CORCH_A",
  "CORCH_C",
  "INDENT",
  "DEDENT",
  "DESIGUAL",
  "READ_INT",
  "READ_FLOAT",
  "READ_BOOL"
  };
}

