
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import java.util.Hashtable;
import java.util.ArrayList;
import ast.*;
import ast.aritmetica.*;
import ast.logica.*;
import ast.relacional.*;
import ast.unario.*;
import ast.read.*;
import ast.literal.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\101\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\006\003\000\002\006\002\000\002\007\004" +
    "\000\002\007\003\000\002\010\005\000\002\010\010\000" +
    "\002\011\005\000\002\011\003\000\002\012\003\000\002" +
    "\012\003\000\002\012\003\000\002\003\004\000\002\003" +
    "\002\000\002\005\005\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\006\000\002\004\006\000" +
    "\002\004\003\000\002\004\003\000\002\027\005\000\002" +
    "\027\010\000\002\013\006\000\002\014\006\000\002\014" +
    "\004\000\002\014\002\000\002\017\002\000\002\015\007" +
    "\000\002\016\006\000\002\016\002\000\002\020\005\000" +
    "\002\020\003\000\002\021\005\000\002\021\003\000\002" +
    "\022\004\000\002\022\003\000\002\023\005\000\002\023" +
    "\005\000\002\023\005\000\002\023\005\000\002\023\005" +
    "\000\002\023\005\000\002\023\003\000\002\024\005\000" +
    "\002\024\005\000\002\024\003\000\002\025\005\000\002" +
    "\025\005\000\002\025\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\026\003\000\002\026\006" +
    "\000\002\026\003\000\002\026\003\000\002\026\003\000" +
    "\002\026\003\000\002\026\005\000\002\026\010\000\002" +
    "\026\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\170\000\014\015\006\016\007\017\013\020\012\021" +
    "\ufffd\001\002\000\004\002\172\001\002\000\004\012\170" +
    "\001\002\000\004\012\ufff6\001\002\000\004\012\ufff5\001" +
    "\002\000\014\015\ufffb\016\ufffb\017\ufffb\020\ufffb\021\ufffb" +
    "\001\002\000\004\021\026\001\002\000\004\052\016\001" +
    "\002\000\004\012\ufff4\001\002\000\014\015\006\016\007" +
    "\017\013\020\012\021\ufffe\001\002\000\014\015\ufffc\016" +
    "\ufffc\017\ufffc\020\ufffc\021\ufffc\001\002\000\004\005\017" +
    "\001\002\000\004\053\020\001\002\000\004\012\021\001" +
    "\002\000\004\004\022\001\002\000\016\013\ufff7\015\ufff7" +
    "\016\ufff7\017\ufff7\020\ufff7\021\ufff7\001\002\000\016\013" +
    "\024\015\ufff9\016\ufff9\017\ufff9\020\ufff9\021\ufff9\001\002" +
    "\000\004\004\025\001\002\000\016\013\ufff8\015\ufff8\016" +
    "\ufff8\017\ufff8\020\ufff8\021\ufff8\001\002\000\006\002\uffff" +
    "\054\030\001\002\000\004\002\000\001\002\000\020\004" +
    "\ufff2\022\ufff2\025\ufff2\027\ufff2\030\ufff2\031\ufff2\055\ufff2" +
    "\001\002\000\020\004\040\022\037\025\032\027\041\030" +
    "\044\031\042\055\034\001\002\000\032\004\uffe3\005\uffe3" +
    "\006\uffe3\007\uffe3\010\uffe3\032\uffe3\034\uffe3\041\uffe3\050" +
    "\uffe3\057\uffe3\060\uffe3\061\uffe3\001\002\000\020\004\uffef" +
    "\022\uffef\025\uffef\027\uffef\030\uffef\031\uffef\055\uffef\001" +
    "\002\000\030\002\ufff1\004\ufff1\022\ufff1\023\ufff1\024\ufff1" +
    "\025\ufff1\026\ufff1\027\ufff1\030\ufff1\031\ufff1\055\ufff1\001" +
    "\002\000\020\004\ufff3\022\ufff3\025\ufff3\027\ufff3\030\ufff3" +
    "\031\ufff3\055\ufff3\001\002\000\020\004\uffee\022\uffee\025" +
    "\uffee\027\uffee\030\uffee\031\uffee\055\uffee\001\002\000\032" +
    "\004\052\005\067\006\061\007\071\010\055\032\053\034" +
    "\070\041\046\050\065\057\060\060\054\061\050\001\002" +
    "\000\006\042\140\052\141\001\002\000\004\050\045\001" +
    "\002\000\020\004\uffea\022\uffea\025\uffea\027\uffea\030\uffea" +
    "\031\uffea\055\uffea\001\002\000\020\004\ufff0\022\ufff0\025" +
    "\ufff0\027\ufff0\030\ufff0\031\ufff0\055\ufff0\001\002\000\020" +
    "\004\uffeb\022\uffeb\025\uffeb\027\uffeb\030\uffeb\031\uffeb\055" +
    "\uffeb\001\002\000\034\004\052\005\067\006\061\007\071" +
    "\010\055\011\056\032\053\034\070\041\046\050\065\057" +
    "\060\060\054\061\050\001\002\000\032\004\052\005\067" +
    "\006\061\007\071\010\055\032\053\034\070\041\046\050" +
    "\065\057\060\060\054\061\050\001\002\000\030\004\uffda" +
    "\022\uffda\025\uffda\027\uffda\030\uffda\031\uffda\037\uffda\040" +
    "\uffda\051\uffda\054\uffda\055\uffda\001\002\000\060\004\uffc4" +
    "\013\uffc4\022\uffc4\025\uffc4\027\uffc4\030\uffc4\031\uffc4\033" +
    "\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\040\uffc4\043\uffc4" +
    "\044\uffc4\045\uffc4\046\uffc4\047\uffc4\051\uffc4\053\uffc4\054" +
    "\uffc4\055\uffc4\056\uffc4\001\002\000\026\004\uffde\022\uffde" +
    "\025\uffde\027\uffde\030\uffde\031\uffde\040\135\051\uffde\054" +
    "\uffde\055\uffde\001\002\000\062\004\uffc9\013\uffc9\022\uffc9" +
    "\025\uffc9\027\uffc9\030\uffc9\031\uffc9\033\uffc9\034\uffc9\035" +
    "\uffc9\036\uffc9\037\uffc9\040\uffc9\043\uffc9\044\uffc9\045\uffc9" +
    "\046\uffc9\047\uffc9\051\uffc9\052\132\053\uffc9\054\uffc9\055" +
    "\uffc9\056\uffc9\001\002\000\004\050\125\001\002\000\060" +
    "\004\uffc5\013\uffc5\022\uffc5\025\uffc5\027\uffc5\030\uffc5\031" +
    "\uffc5\033\uffc5\034\uffc5\035\uffc5\036\uffc5\037\uffc5\040\uffc5" +
    "\043\uffc5\044\uffc5\045\uffc5\046\uffc5\047\uffc5\051\uffc5\053" +
    "\uffc5\054\uffc5\055\uffc5\056\uffc5\001\002\000\060\004\uffca" +
    "\013\uffca\022\uffca\025\uffca\027\uffca\030\uffca\031\uffca\033" +
    "\uffca\034\uffca\035\uffca\036\uffca\037\uffca\040\uffca\043\uffca" +
    "\044\uffca\045\uffca\046\uffca\047\uffca\051\uffca\053\uffca\054" +
    "\uffca\055\uffca\056\uffca\001\002\000\004\051\124\001\002" +
    "\000\004\051\123\001\002\000\060\004\uffc6\013\uffc6\022" +
    "\uffc6\025\uffc6\027\uffc6\030\uffc6\031\uffc6\033\uffc6\034\uffc6" +
    "\035\uffc6\036\uffc6\037\uffc6\040\uffc6\043\uffc6\044\uffc6\045" +
    "\uffc6\046\uffc6\047\uffc6\051\uffc6\053\uffc6\054\uffc6\055\uffc6" +
    "\056\uffc6\001\002\000\060\004\uffcb\013\uffcb\022\uffcb\025" +
    "\uffcb\027\uffcb\030\uffcb\031\uffcb\033\uffcb\034\uffcb\035\uffcb" +
    "\036\uffcb\037\uffcb\040\uffcb\043\uffcb\044\uffcb\045\uffcb\046" +
    "\uffcb\047\uffcb\051\uffcb\053\uffcb\054\uffcb\055\uffcb\056\uffcb" +
    "\001\002\000\030\004\uffdc\022\uffdc\025\uffdc\027\uffdc\030" +
    "\uffdc\031\uffdc\037\121\040\uffdc\051\uffdc\054\uffdc\055\uffdc" +
    "\001\002\000\060\004\uffcd\013\uffcd\022\uffcd\025\uffcd\027" +
    "\uffcd\030\uffcd\031\uffcd\033\uffcd\034\uffcd\035\uffcd\036\uffcd" +
    "\037\uffcd\040\uffcd\043\uffcd\044\uffcd\045\uffcd\046\uffcd\047" +
    "\uffcd\051\uffcd\053\uffcd\054\uffcd\055\uffcd\056\uffcd\001\002" +
    "\000\060\004\uffd0\013\uffd0\022\uffd0\025\uffd0\027\uffd0\030" +
    "\uffd0\031\uffd0\033\uffd0\034\uffd0\035\107\036\110\037\uffd0" +
    "\040\uffd0\043\uffd0\044\uffd0\045\uffd0\046\uffd0\047\uffd0\051" +
    "\uffd0\053\uffd0\054\uffd0\055\uffd0\056\uffd0\001\002\000\032" +
    "\004\052\005\067\006\061\007\071\010\055\032\053\034" +
    "\070\041\046\050\065\057\060\060\054\061\050\001\002" +
    "\000\050\004\uffd3\022\uffd3\025\uffd3\027\uffd3\030\uffd3\031" +
    "\uffd3\033\076\034\077\037\uffd3\040\uffd3\043\101\044\102" +
    "\045\100\046\073\047\074\051\uffd3\054\uffd3\055\uffd3\056" +
    "\075\001\002\000\060\004\uffcc\013\uffcc\022\uffcc\025\uffcc" +
    "\027\uffcc\030\uffcc\031\uffcc\033\uffcc\034\uffcc\035\uffcc\036" +
    "\uffcc\037\uffcc\040\uffcc\043\uffcc\044\uffcc\045\uffcc\046\uffcc" +
    "\047\uffcc\051\uffcc\053\uffcc\054\uffcc\055\uffcc\056\uffcc\001" +
    "\002\000\030\004\052\005\067\006\061\007\071\010\055" +
    "\032\053\034\070\050\065\057\060\060\054\061\050\001" +
    "\002\000\060\004\uffc7\013\uffc7\022\uffc7\025\uffc7\027\uffc7" +
    "\030\uffc7\031\uffc7\033\uffc7\034\uffc7\035\uffc7\036\uffc7\037" +
    "\uffc7\040\uffc7\043\uffc7\044\uffc7\045\uffc7\046\uffc7\047\uffc7" +
    "\051\uffc7\053\uffc7\054\uffc7\055\uffc7\056\uffc7\001\002\000" +
    "\060\004\uffc1\013\uffc1\022\uffc1\025\uffc1\027\uffc1\030\uffc1" +
    "\031\uffc1\033\uffc1\034\uffc1\035\uffc1\036\uffc1\037\uffc1\040" +
    "\uffc1\043\uffc1\044\uffc1\045\uffc1\046\uffc1\047\uffc1\051\uffc1" +
    "\053\uffc1\054\uffc1\055\uffc1\056\uffc1\001\002\000\030\004" +
    "\052\005\067\006\061\007\071\010\055\032\053\034\070" +
    "\050\065\057\060\060\054\061\050\001\002\000\030\004" +
    "\052\005\067\006\061\007\071\010\055\032\053\034\070" +
    "\050\065\057\060\060\054\061\050\001\002\000\030\004" +
    "\052\005\067\006\061\007\071\010\055\032\053\034\070" +
    "\050\065\057\060\060\054\061\050\001\002\000\030\004" +
    "\052\005\067\006\061\007\071\010\055\032\053\034\070" +
    "\050\065\057\060\060\054\061\050\001\002\000\030\004" +
    "\052\005\067\006\061\007\071\010\055\032\053\034\070" +
    "\050\065\057\060\060\054\061\050\001\002\000\030\004" +
    "\052\005\067\006\061\007\071\010\055\032\053\034\070" +
    "\050\065\057\060\060\054\061\050\001\002\000\030\004" +
    "\052\005\067\006\061\007\071\010\055\032\053\034\070" +
    "\050\065\057\060\060\054\061\050\001\002\000\030\004" +
    "\052\005\067\006\061\007\071\010\055\032\053\034\070" +
    "\050\065\057\060\060\054\061\050\001\002\000\034\004" +
    "\uffd8\022\uffd8\025\uffd8\027\uffd8\030\uffd8\031\uffd8\033\076" +
    "\034\077\037\uffd8\040\uffd8\051\uffd8\054\uffd8\055\uffd8\001" +
    "\002\000\034\004\uffd9\022\uffd9\025\uffd9\027\uffd9\030\uffd9" +
    "\031\uffd9\033\076\034\077\037\uffd9\040\uffd9\051\uffd9\054" +
    "\uffd9\055\uffd9\001\002\000\034\004\uffd7\022\uffd7\025\uffd7" +
    "\027\uffd7\030\uffd7\031\uffd7\033\076\034\077\037\uffd7\040" +
    "\uffd7\051\uffd7\054\uffd7\055\uffd7\001\002\000\060\004\uffd1" +
    "\013\uffd1\022\uffd1\025\uffd1\027\uffd1\030\uffd1\031\uffd1\033" +
    "\uffd1\034\uffd1\035\107\036\110\037\uffd1\040\uffd1\043\uffd1" +
    "\044\uffd1\045\uffd1\046\uffd1\047\uffd1\051\uffd1\053\uffd1\054" +
    "\uffd1\055\uffd1\056\uffd1\001\002\000\030\004\052\005\067" +
    "\006\061\007\071\010\055\032\053\034\070\050\065\057" +
    "\060\060\054\061\050\001\002\000\030\004\052\005\067" +
    "\006\061\007\071\010\055\032\053\034\070\050\065\057" +
    "\060\060\054\061\050\001\002\000\060\004\uffce\013\uffce" +
    "\022\uffce\025\uffce\027\uffce\030\uffce\031\uffce\033\uffce\034" +
    "\uffce\035\uffce\036\uffce\037\uffce\040\uffce\043\uffce\044\uffce" +
    "\045\uffce\046\uffce\047\uffce\051\uffce\053\uffce\054\uffce\055" +
    "\uffce\056\uffce\001\002\000\060\004\uffcf\013\uffcf\022\uffcf" +
    "\025\uffcf\027\uffcf\030\uffcf\031\uffcf\033\uffcf\034\uffcf\035" +
    "\uffcf\036\uffcf\037\uffcf\040\uffcf\043\uffcf\044\uffcf\045\uffcf" +
    "\046\uffcf\047\uffcf\051\uffcf\053\uffcf\054\uffcf\055\uffcf\056" +
    "\uffcf\001\002\000\060\004\uffd2\013\uffd2\022\uffd2\025\uffd2" +
    "\027\uffd2\030\uffd2\031\uffd2\033\uffd2\034\uffd2\035\107\036" +
    "\110\037\uffd2\040\uffd2\043\uffd2\044\uffd2\045\uffd2\046\uffd2" +
    "\047\uffd2\051\uffd2\053\uffd2\054\uffd2\055\uffd2\056\uffd2\001" +
    "\002\000\034\004\uffd4\022\uffd4\025\uffd4\027\uffd4\030\uffd4" +
    "\031\uffd4\033\076\034\077\037\uffd4\040\uffd4\051\uffd4\054" +
    "\uffd4\055\uffd4\001\002\000\034\004\uffd5\022\uffd5\025\uffd5" +
    "\027\uffd5\030\uffd5\031\uffd5\033\076\034\077\037\uffd5\040" +
    "\uffd5\051\uffd5\054\uffd5\055\uffd5\001\002\000\034\004\uffd6" +
    "\022\uffd6\025\uffd6\027\uffd6\030\uffd6\031\uffd6\033\076\034" +
    "\077\037\uffd6\040\uffd6\051\uffd6\054\uffd6\055\uffd6\001\002" +
    "\000\004\051\120\001\002\000\060\004\uffc3\013\uffc3\022" +
    "\uffc3\025\uffc3\027\uffc3\030\uffc3\031\uffc3\033\uffc3\034\uffc3" +
    "\035\uffc3\036\uffc3\037\uffc3\040\uffc3\043\uffc3\044\uffc3\045" +
    "\uffc3\046\uffc3\047\uffc3\051\uffc3\053\uffc3\054\uffc3\055\uffc3" +
    "\056\uffc3\001\002\000\032\004\052\005\067\006\061\007" +
    "\071\010\055\032\053\034\070\041\046\050\065\057\060" +
    "\060\054\061\050\001\002\000\026\004\uffdd\022\uffdd\025" +
    "\uffdd\027\uffdd\030\uffdd\031\uffdd\040\uffdd\051\uffdd\054\uffdd" +
    "\055\uffdd\001\002\000\020\004\uffed\022\uffed\025\uffed\027" +
    "\uffed\030\uffed\031\uffed\055\uffed\001\002\000\020\004\uffec" +
    "\022\uffec\025\uffec\027\uffec\030\uffec\031\uffec\055\uffec\001" +
    "\002\000\030\004\052\005\067\006\061\007\071\010\055" +
    "\032\053\034\070\050\065\057\060\060\054\061\050\001" +
    "\002\000\010\013\127\033\076\034\077\001\002\000\004" +
    "\007\130\001\002\000\004\051\131\001\002\000\060\004" +
    "\uffc2\013\uffc2\022\uffc2\025\uffc2\027\uffc2\030\uffc2\031\uffc2" +
    "\033\uffc2\034\uffc2\035\uffc2\036\uffc2\037\uffc2\040\uffc2\043" +
    "\uffc2\044\uffc2\045\uffc2\046\uffc2\047\uffc2\051\uffc2\053\uffc2" +
    "\054\uffc2\055\uffc2\056\uffc2\001\002\000\030\004\052\005" +
    "\067\006\061\007\071\010\055\032\053\034\070\050\065" +
    "\057\060\060\054\061\050\001\002\000\010\033\076\034" +
    "\077\053\134\001\002\000\060\004\uffc8\013\uffc8\022\uffc8" +
    "\025\uffc8\027\uffc8\030\uffc8\031\uffc8\033\uffc8\034\uffc8\035" +
    "\uffc8\036\uffc8\037\uffc8\040\uffc8\043\uffc8\044\uffc8\045\uffc8" +
    "\046\uffc8\047\uffc8\051\uffc8\053\uffc8\054\uffc8\055\uffc8\056" +
    "\uffc8\001\002\000\032\004\052\005\067\006\061\007\071" +
    "\010\055\032\053\034\070\041\046\050\065\057\060\060" +
    "\054\061\050\001\002\000\024\004\uffdf\022\uffdf\025\uffdf" +
    "\027\uffdf\030\uffdf\031\uffdf\051\uffdf\054\uffdf\055\uffdf\001" +
    "\002\000\030\004\uffdb\022\uffdb\025\uffdb\027\uffdb\030\uffdb" +
    "\031\uffdb\037\uffdb\040\uffdb\051\uffdb\054\uffdb\055\uffdb\001" +
    "\002\000\032\004\052\005\067\006\061\007\071\010\055" +
    "\032\053\034\070\041\046\050\065\057\060\060\054\061" +
    "\050\001\002\000\030\004\052\005\067\006\061\007\071" +
    "\010\055\032\053\034\070\050\065\057\060\060\054\061" +
    "\050\001\002\000\010\033\076\034\077\053\143\001\002" +
    "\000\004\042\144\001\002\000\032\004\052\005\067\006" +
    "\061\007\071\010\055\032\053\034\070\041\046\050\065" +
    "\057\060\060\054\061\050\001\002\000\020\004\uffe8\022" +
    "\uffe8\025\uffe8\027\uffe8\030\uffe8\031\uffe8\055\uffe8\001\002" +
    "\000\020\004\uffe9\022\uffe9\025\uffe9\027\uffe9\030\uffe9\031" +
    "\uffe9\055\uffe9\001\002\000\004\054\030\001\002\000\024" +
    "\004\uffe4\022\uffe4\023\151\024\153\025\uffe4\027\uffe4\030" +
    "\uffe4\031\uffe4\055\uffe4\001\002\000\004\054\030\001\002" +
    "\000\020\004\uffe7\022\uffe7\025\uffe7\027\uffe7\030\uffe7\031" +
    "\uffe7\055\uffe7\001\002\000\032\004\052\005\067\006\061" +
    "\007\071\010\055\032\053\034\070\041\046\050\065\057" +
    "\060\060\054\061\050\001\002\000\004\054\030\001\002" +
    "\000\024\004\uffe4\022\uffe4\023\151\024\153\025\uffe4\027" +
    "\uffe4\030\uffe4\031\uffe4\055\uffe4\001\002\000\020\004\uffe6" +
    "\022\uffe6\025\uffe6\027\uffe6\030\uffe6\031\uffe6\055\uffe6\001" +
    "\002\000\020\004\uffe5\022\uffe5\025\uffe5\027\uffe5\030\uffe5" +
    "\031\uffe5\055\uffe5\001\002\000\032\004\052\005\067\006" +
    "\061\007\071\010\055\032\053\034\070\041\046\050\065" +
    "\057\060\060\054\061\050\001\002\000\004\054\030\001" +
    "\002\000\022\004\uffe0\022\uffe0\025\uffe0\026\163\027\uffe0" +
    "\030\uffe0\031\uffe0\055\uffe0\001\002\000\032\004\052\005" +
    "\067\006\061\007\071\010\055\032\053\034\070\041\046" +
    "\050\065\057\060\060\054\061\050\001\002\000\020\004" +
    "\uffe2\022\uffe2\025\uffe2\027\uffe2\030\uffe2\031\uffe2\055\uffe2" +
    "\001\002\000\004\054\030\001\002\000\022\004\uffe0\022" +
    "\uffe0\025\uffe0\026\163\027\uffe0\030\uffe0\031\uffe0\055\uffe0" +
    "\001\002\000\020\004\uffe1\022\uffe1\025\uffe1\027\uffe1\030" +
    "\uffe1\031\uffe1\055\uffe1\001\002\000\004\004\022\001\002" +
    "\000\016\013\024\015\ufffa\016\ufffa\017\ufffa\020\ufffa\021" +
    "\ufffa\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\170\000\014\002\003\006\010\007\013\010\007\012" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\010\014" +
    "\012\004\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\022\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\026\001\001\000\002\001\001" +
    "\000\004\003\030\001\001\000\012\004\034\013\042\015" +
    "\032\027\035\001\001\000\004\017\157\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\020\146\021\050\022\061\023\046\024\065" +
    "\025\063\026\062\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\020\056\021\050\022\061\023\046\024\065\025" +
    "\063\026\062\001\001\000\014\022\136\023\046\024\065" +
    "\025\063\026\062\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\020" +
    "\116\021\050\022\061\023\046\024\065\025\063\026\062" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\026" +
    "\071\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\024\115\025\063\026\062\001\001\000\010\024\114\025" +
    "\063\026\062\001\001\000\010\024\113\025\063\026\062" +
    "\001\001\000\006\025\112\026\062\001\001\000\006\025" +
    "\105\026\062\001\001\000\010\024\104\025\063\026\062" +
    "\001\001\000\010\024\103\025\063\026\062\001\001\000" +
    "\010\024\102\025\063\026\062\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\026\111\001\001\000\004\026\110\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\021\121\022\061\023\046\024" +
    "\065\025\063\026\062\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\024\125\025\063\026" +
    "\062\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\024\132\025\063\026" +
    "\062\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\020\135\021\050\022\061\023\046\024\065\025\063\026" +
    "\062\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\020\145\021\050\022\061\023\046\024\065\025\063\026" +
    "\062\001\001\000\010\024\141\025\063\026\062\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\020\144\021" +
    "\050\022\061\023\046\024\065\025\063\026\062\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\147\001" +
    "\001\000\004\014\151\001\001\000\004\005\156\001\001" +
    "\000\002\001\001\000\020\020\153\021\050\022\061\023" +
    "\046\024\065\025\063\026\062\001\001\000\004\005\154" +
    "\001\001\000\004\014\155\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\020\160\021\050\022\061\023\046" +
    "\024\065\025\063\026\062\001\001\000\004\005\161\001" +
    "\001\000\004\016\163\001\001\000\020\020\164\021\050" +
    "\022\061\023\046\024\065\025\063\026\062\001\001\000" +
    "\002\001\001\000\004\005\165\001\001\000\004\016\166" +
    "\001\001\000\002\001\001\000\004\011\170\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public static SymbolTable tablaSimbolos = new SymbolTable();

    // public ValidatorDataType validador = new ValidatorDataType();

    public static ArrayList<Declaracion> declaracionesMacro = new ArrayList<>();

    public void syntax_error(Symbol s){
        System.out.println("Error en la linea "+ (s.left+1)+ " Columna "+ s.right+ ". Valor simbolo '"
        +s.value+"' . Simbolo n° "+s.sym+ " no reconocido." );
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.out.println("Error en la linea "+ (s.left+1)+ " Columna "+ s.right+ ". Valor simbolo '"
        +s.value+"' . Simbolo n° "+s.sym+ " no reconocido." );
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {


    Hashtable table = new Hashtable();
    String tam = "0";     // Tamaño del array
    int nivelLoop = 0;    // Controla breaks/continues

    // Estructura auxiliar para retornar los nodos transformados y su tipo resultante
    public class OpResult {
        public Expresion izq;
        public Expresion der;
        public String tipoLLVM;
        public OpResult(Expresion i, Expresion d, String t) {
            this.izq = i; this.der = d; this.tipoLLVM = t;
        }
    }

    // 🌟 HELPER ARITMÉTICO: Resuelve Coerción, Broadcasting y Validación de Arrays
    public OpResult verificarYCoercer(Expresion e1, Expresion e2) {
        String t1 = e1.getTipo(); // Asume que tus nodos retornan "INT", "FLOAT", "BOOLEAN" o "\d+" (dimensión)
        String t2 = e2.getTipo();

        if ("BOOLEAN".equals(t1) || "BOOLEAN".equals(t2)) {
            throw new RuntimeException("ERROR SEMÁNTICO: Operación aritmética inválida con tipos BOOLEAN.");
        }

        boolean esArray1 = t1.matches("\\d+");
        boolean esArray2 = t2.matches("\\d+");

        // Caso 1: Ambos son Arrays (FLOAT_ARRAY) -> Deben medir igual
        if (esArray1 && esArray2) {
            if (!t1.equals(t2)) {
                throw new RuntimeException("ERROR SEMÁNTICO: Dimensiones de arreglos incompatibles (" + t1 + " vs " + t2 + ").");
            }
            return new OpResult(e1, e2, t1); // El tipo resultante conserva la dimensión ("10", "50", etc.)
        }

        // Caso 2: Broadcasting (Array operado con Escalar) -> Inserta conversión si el escalar es INT
        if (esArray1) {
            Expresion der = "INT".equals(t2) ? new ConversionFloat(e2) : e2;
            return new OpResult(e1, der, t1);
        }
        if (esArray2) {
            Expresion izq = "INT".equals(t1) ? new ConversionFloat(e1) : e1;
            return new OpResult(izq, e2, t2);
        }

        // Caso 3: Escalares Puros (INT vs FLOAT) -> Coerción estándar
        if ("FLOAT".equals(t1) || "DOUBLE".equals(t1)) {
            Expresion der = "INT".equals(t2) ? new ConversionFloat(e2) : e2;
            return new OpResult(e1, der, "FLOAT");
        }
        if ("FLOAT".equals(t2) || "DOUBLE".equals(t2)) {
            Expresion izq = "INT".equals(t1) ? new ConversionFloat(e1) : e1;
            return new OpResult(izq, e2, "FLOAT");
        }

        return new OpResult(e1, e2, "INT"); // Ambos son enteros (INT)
    }

    // 🌟 HELPER RELACIONAL: Valida comparaciones entre vectores y escalares
    public OpResult verificarRelacional(Expresion e1, Expresion e2) {
        String t1 = e1.getTipo();
        String t2 = e2.getTipo();

        boolean esArray1 = t1.matches("\\d+");
        boolean esArray2 = t2.matches("\\d+");

        if (esArray1 && esArray2 && !t1.equals(t2)) {
            throw new RuntimeException("ERROR SEMÁNTICO: No se pueden comparar arreglos de distintas dimensiones.");
        }

        String tipoFinal = "INT"; // "int" por defecto para tu backend
        Expresion izq = e1;
        Expresion der = e2;

        if ("INT".equals(t1) && ("FLOAT".equals(t2) || esArray2)) {
            izq = new ConversionFloat(e1);
            tipoFinal = "FLOAT";
        } else if ("INT".equals(t2) && ("FLOAT".equals(t1) || esArray1)) {
            der = new ConversionFloat(e2);
            tipoFinal = "FLOAT";
        } else if ("FLOAT".equals(t1) || "FLOAT".equals(t2) || esArray1 || esArray2) {
            tipoFinal = "FLOAT";
        }

        return new OpResult(izq, der, tipoFinal);
    }

  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Programa start_val = (Programa)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_variables PROGRAM bloque 
            {
              Programa RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<Declaracion> v = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Sentencia> l = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 0.1: programa -> PROGRAM lista_sentencias");
    System.out.printf("REGLA 0.1: programa -> %s%n%n", l);
    if (v == null) {
            v = new ArrayList<Declaracion>();
        }
    RESULT = new Programa("MiProyecto", v, declaracionesMacro, l);


              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= lista_variables PROGRAM 
            {
              Programa RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Declaracion> v = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    RESULT = new Programa("MiProyecto", v, declaracionesMacro, null);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_variables ::= lista_de_lineas 
            {
              ArrayList<Declaracion> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Declaracion> l = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 16: lista_variables -> lista_de_lineas");
    RESULT = l;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_variables",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_variables ::= 
            {
              ArrayList<Declaracion> RESULT =null;
		
    System.out.println("REGLA 17: lista_variables -> vacio");
    RESULT = new ArrayList<Declaracion>();

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_variables",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_de_lineas ::= lista_de_lineas variable 
            {
              ArrayList<Declaracion> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Declaracion> l = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Declaracion v = (Declaracion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 18: lista_de_lineas -> lista_de_lineas variable");
    l.add(v); // Agrega la nueva declaración a la lista
    RESULT = l;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_de_lineas",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_de_lineas ::= variable 
            {
              ArrayList<Declaracion> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Declaracion v = (Declaracion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 19: lista_de_lineas -> variable");
    ArrayList<Declaracion> lista = new ArrayList<>();
    lista.add(v);
    RESULT = lista;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_de_lineas",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // variable ::= tipo_datos DOS_PUNTOS lista_de_variable 
            {
              Declaracion RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int nombresleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nombresright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<String> nombres = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
System.out.println("REGLA 20: variable -> tipo_datos DOS_PUNTOS lista_de_variable");
for (String id : nombres) {
        if (tablaSimbolos.exists(id)) {
            System.err.println("Error: Variable '" + id + "' ya declarada.");
        } else {
            tablaSimbolos.add("ID", id, t, null, null);
            System.out.println("Declarado: " + id + " de tipo " + t);
        }
    }
    RESULT = new Declaracion(t, nombres);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // variable ::= TYPE_ARRAY CORCH_A ENTERO CORCH_C DOS_PUNTOS lista_de_variable 
            {
              Declaracion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nombresleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nombresright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<String> nombres = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
System.out.println("REGLA 15: Creacion de array");
String tipoEspecial = "FLOAT_ARRAY";
    for (String id : nombres) {
        if (tablaSimbolos.exists(id)) {
            System.err.println("Error: Variable '" + id + "' ya declarada.");
        } else {
            tablaSimbolos.add("ID", id, tipoEspecial, null, String.valueOf(e));
            System.out.println("Declarado: " + id + " de tipo " + tipoEspecial);
        }
    }
    RESULT = new DeclaracionArray(e, nombres);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_de_variable ::= lista_de_variable COMA ID 
            {
              ArrayList<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<String> list = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
      list.add(e);
      RESULT = list;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_de_variable",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_de_variable ::= ID 
            {
              ArrayList<String> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList<String> lista = new ArrayList<>();
        lista.add(n);
        RESULT = lista;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_de_variable",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo_datos ::= TYPE_INT 
            {
              String RESULT =null;
		 RESULT = "INT";  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_datos",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // tipo_datos ::= TYPE_FLOAT 
            {
              String RESULT =null;
		 RESULT = "FLOAT";   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_datos",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // tipo_datos ::= TYPE_BOOL 
            {
              String RESULT =null;
		 RESULT = "BOOLEAN"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_datos",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // lista_sentencias ::= lista_sentencias sentencia 
            {
              ArrayList<Sentencia> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Sentencia> l = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia s = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 1.1: lista_sentencias -> lista_sentencias sentencia");
    System.out.printf("REGLA 1.1: lista_sentencias -> %s %s%n%n", l, s);
    l.add(s);
    RESULT = l;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_sentencias ::= 
            {
              ArrayList<Sentencia> RESULT =null;
		
      RESULT = new ArrayList<Sentencia>();
  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // bloque ::= INDENT lista_sentencias DEDENT 
            {
              ArrayList<Sentencia> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Sentencia> l = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    System.out.println("REGLA 8: bloque -> INDENT lista_sentencias DEDENT");
    System.out.printf("REGLA 8: bloque -> %s%n%n", l);
    RESULT = l;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= sentencia_if 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia s = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 3.1: sentencia -> sentencia_if");
    System.out.printf("REGLA 3.1: sentencia -> %s%n%n", s);
    RESULT = s;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= sentencia_while 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia s = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 3.2: sentencia -> sentencia_while");
    System.out.printf("REGLA 3.2: sentencia -> %s%n%n", s);
    RESULT = s;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= asignacion 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia s = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 3.3: sentencia -> asignacion");
    System.out.printf("REGLA 3.3: sentencia -> %s%n%n", s);
    RESULT = s;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= PRINT PAREN_A expr_logica PAREN_C 
            {
              Sentencia RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    System.out.println("REGLA 3.4: sentencia -> PRINT expresion");
    System.out.printf("REGLA 3.4: sentencia -> %s%n%n", e);

    String tipo = e.getTipo();
    String tipoLLVM = "";
    tam = "0"; // Crucial: Resetear para evitar arrastrar tamaños de prints anteriores

    if (tipo != null && tipo.matches("\\d+")) { // Si el tipo es un número, es un array (su tamaño)
        tipoLLVM = "array";
        tam = tipo; // Asignamos el tamaño extraído directamente del tipo del nodo
    } else {
        tipoLLVM = tipo;
    }
    RESULT = new SentenciaPrint(e, tipoLLVM, tam);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= PRINT PAREN_A STRING PAREN_C 
            {
              Sentencia RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
           if (!tablaSimbolos.exists(str)) {
               String texto;
               // Pasamos null en el ID para que tu método add() genere la llave "_contenido"
               texto = str.replace("\n", " ");
               texto = texto.replace("\r", "");
               tablaSimbolos.add("CTE_STR", null, "STRING", texto, null);
               System.out.println("REGLA: PRINT -> Nueva cadena guardada: " + str);
           } else {
               System.out.println("REGLA: PRINT -> La cadena ya existe en la tabla: " + str);
           }
           RESULT = RESULT = new SentenciaPrint(new StringLiteral(str), "i8");;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= BREAK 
            {
              Sentencia RESULT =null;
		
    System.out.println("REGLA 3.5: sentencia -> BREAK");
    System.out.printf("REGLA 3.5: sentencia -> break%n%n");
    if (nivelLoop == 0) {
        throw new RuntimeException("ERROR SEMÁNTICO: BREAK fuera de un ciclo.");
    }
    System.out.println("BREAK válido, nivelLoop = " + nivelLoop);
    RESULT = new SentenciaBreak();

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= CONTINUE 
            {
              Sentencia RESULT =null;
		
    System.out.println("REGLA 3.6: sentencia -> CONTINUE");
    System.out.printf("REGLA 3.6: sentencia -> continue%n%n");
    if (nivelLoop == 0) {
        throw new RuntimeException("ERROR SEMÁNTICO: CONTINUE fuera de un ciclo.");
    }
    RESULT = new SentenciaContinue();

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // asignacion ::= ID IGUAL expr_logica 
            {
              Sentencia RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 15.1: sentencia -> ID = expresion");

    // 1. Guardamos el tipo de nacimiento real para el idTipo del Nodo
    String tipoOriginalID = tablaSimbolos.getTipo(id);

    // Obtener tipo destino para las validaciones locales
    String tDest = tipoOriginalID;
    if ("FLOAT_ARRAY".equals(tDest)) {
        tDest = tablaSimbolos.getTamano(id);
    }

    String tExp = e.getTipo();
    boolean esArrayDest = tDest.matches("\\d+");
    boolean esArrayExp = tExp.matches("\\d+");

    if (esArrayDest) {
        if (esArrayExp && !tDest.equals(tExp)) {
            throw new RuntimeException("ERROR SEMÁNTICO: Dimensiones incompatibles en asignación de arreglos.");
        }
        if (!esArrayExp && "BOOLEAN".equals(tExp)) {
            throw new RuntimeException("ERROR SEMÁNTICO: No se puede hacer broadcasting de un BOOLEAN a un FLOAT_ARRAY.");
        }
    } else {
        if (esArrayExp) {
            throw new RuntimeException("ERROR SEMÁNTICO: No se puede asignar un arreglo a la variable escalar '" + id + "'.");
        }
        if ("BOOLEAN".equals(tDest) && !"BOOLEAN".equals(tExp)) {
            throw new RuntimeException("ERROR SEMÁNTICO: Tipos incompatibles para variable BOOLEAN '" + id + "'.");
        }
    }

    // Coerción en asignación escalar
    Expresion exprFinal = e;
    String tipoFinalExpresion = tExp; // Por defecto es el tipo de la expresión original

    if ("FLOAT".equals(tDest) && "INT".equals(tExp)) {
        exprFinal = new ConversionFloat(e);
        tipoFinalExpresion = "FLOAT"; // 🌟 Ahora la expresión fue promovida a FLOAT
    }

    // 🌟 RESULTADO CORREGIDO:
    // id = nombre variable
    // exprFinal = el nodo (casteado o no)
    // tipoOriginalID = "INT", "FLOAT", "FLOAT_ARRAY" (Lo que necesita idTipo)
    // tipoFinalExpresion = "INT", "FLOAT", "BOOLEAN" o la dimensión del arreglo ("10")
    RESULT = new Asignacion(id, exprFinal, tipoOriginalID, tipoFinalExpresion);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // asignacion ::= ID CORCH_A expr_arit CORCH_C IGUAL expr_logica 
            {
              Sentencia RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion ex = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 15.2: Asignacion ARRAY celdas");

    if (!"INT".equals(exp.getTipo())) {
        throw new RuntimeException("ERROR SEMÁNTICO: El índice del arreglo '" + i + "' debe ser tipo INT.");
    }
    if (!"FLOAT_ARRAY".equals(tablaSimbolos.getTipo(i))) {
        throw new RuntimeException("ERROR SEMÁNTICO: '" + i + "' no es un arreglo.");
    }
    if ("BOOLEAN".equals(ex.getTipo())) {
        throw new RuntimeException("ERROR SEMÁNTICO: Tipo BOOLEAN incompatible para celda FLOAT.");
    }

    Expresion valFinal = ex;
    if ("INT".equals(ex.getTipo())) {
        valFinal = new ConversionFloat(ex);
    }

    RESULT = new AsignacionArray(i, exp, valFinal, tablaSimbolos.getTamano(i));

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia_if ::= IF expr_logica bloque sentencia_elif 
            {
              Sentencia RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Sentencia> b = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int s_elifleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int s_elifright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Sentencia> s_elif = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 4: sentencia_if -> IF expresion bloque sentencia_elif");
    System.out.printf("REGLA 4: if %s then %s %s%n%n", e, b, s_elif);
    RESULT = new SentenciaIf(e, b, s_elif);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia_elif ::= ELIF expr_logica bloque sentencia_elif 
            {
              ArrayList<Sentencia> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Sentencia> b = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Sentencia> s = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 5.1: sentencia_elif -> ELIF expresion bloque sentencia_elif");
    System.out.printf("REGLA 5.1: elif %s then %s %s%n%n", e, b, s);
    // Creamos una lista que contendrá el bloque del ELIF transformado en un IF
        ArrayList<Sentencia> listaElif = new ArrayList<>();

        // El ELIF se convierte en un objeto SentenciaIf
        // (el cual a su vez recibe la lista 's' para sus propios elses)
        SentenciaIf nodoElif = new SentenciaIf(e, b, s);

        listaElif.add(nodoElif);
        RESULT = listaElif;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_elif",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia_elif ::= ELSE bloque 
            {
              ArrayList<Sentencia> RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Sentencia> b = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 5.2: sentencia_elif -> ELSE bloque");
    System.out.printf("REGLA 5.2: else %s%n%n", b);
    RESULT = b;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_elif",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia_elif ::= 
            {
              ArrayList<Sentencia> RESULT =null;
		
    System.out.println("REGLA 5.3: sentencia_elif -> epsilon");
    RESULT = null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_elif",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // inicio_loop ::= 
            {
              Object RESULT =null;
		
    nivelLoop++;
    System.out.println("Entrando a loop, nivelLoop = " + nivelLoop);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicio_loop",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia_while ::= WHILE inicio_loop expr_logica bloque sentencia_alt 
            {
              Sentencia RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Sentencia> b = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int altleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int altright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		SentenciaAlt alt = (SentenciaAlt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 6: sentencia_while -> WHILE expresion bloque");
    System.out.printf("REGLA 6: while %s do %s%n%n", e, b);
    nivelLoop--;                              // ← decrementar al salir
    RESULT = new SentenciaWhile(e, b, alt);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_while",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia_alt ::= ALT_WHILE expr_logica bloque sentencia_alt 
            {
              SentenciaAlt RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Sentencia> b = (ArrayList<Sentencia>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		SentenciaAlt resto = (SentenciaAlt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 7: sentencia_alt -> ALT_WHILE expresion bloque");
    System.out.printf("REGLA 7: alt_while %s do %s%n%n", e, b);
    RESULT = new SentenciaAlt(e, b, resto);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_alt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sentencia_alt ::= 
            {
              SentenciaAlt RESULT =null;
		
      RESULT = null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_alt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr_logica ::= expr_and OR expr_logica 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 10.1: expr_logica -> expr_and OR expr_logica");

    // Como e1 ya tiene su tipo LLVM adentro ("INT", "FLOAT", "BOOLEAN"),
    // se lo pasás directamente al constructor. ¡En una sola línea!
    RESULT = new OperacionOr(e1, e2, e1.getTipo());

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_logica",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr_logica ::= expr_and 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_logica",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr_and ::= expr_not AND expr_and 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 10.2: expr_and -> expr_not AND expr_and");

    // Lo mismo para el AND: tomás el tipo LLVM de e1 directamente
    RESULT = new OperacionAnd(e1, e2, e1.getTipo());

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_and",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr_and ::= expr_not 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_and",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr_not ::= NOT expr_not 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 10.3: expr_logica -> NOT expr_relacional");
    System.out.printf("REGLA 10.3: expr_logica -> NOT %s%n%n", e);
    RESULT = new NotLogico(e);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_not",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr_not ::= expr_relacional 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 10.4: expr_logica -> expr_relacional");
    System.out.printf("REGLA 10.4: expr_logica -> %s%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_not",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr_relacional ::= expr_arit IGUALDAD expr_arit 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarRelacional(e1, e2);
    RESULT = new Igualdad(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr_relacional ::= expr_arit MAYOR expr_arit 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarRelacional(e1, e2);
    RESULT = new Mayor(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr_relacional ::= expr_arit MENOR expr_arit 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarRelacional(e1, e2);
    RESULT = new Menor(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr_relacional ::= expr_arit MAYORIGUAL expr_arit 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarRelacional(e1, e2);
    RESULT = new MayorIgual(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr_relacional ::= expr_arit MENORIGUAL expr_arit 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarRelacional(e1, e2);
    RESULT = new MenorIgual(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr_relacional ::= expr_arit DESIGUAL expr_arit 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarRelacional(e1, e2);
    RESULT = new Desigual(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr_relacional ::= expr_arit 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_relacional",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr_arit ::= expr_arit OP_SUMA termino 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarYCoercer(e1, e2);
    RESULT = new Suma(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr_arit ::= expr_arit OP_RESTA termino 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarYCoercer(e1, e2);
    RESULT = new Resta(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr_arit ::= termino 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_arit",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // termino ::= termino OP_MULTI factor 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarYCoercer(e1, e2);
    RESULT = new Multiplicacion(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // termino ::= termino OP_DIV factor 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    OpResult res = verificarYCoercer(e1, e2);
    RESULT = new Division(res.izq, res.der, res.tipoLLVM);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // termino ::= factor 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // factor ::= ENTERO 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.1: factor -> ENTERO");
    System.out.printf("REGLA 14.1: factor -> %s%n%n", e);
    RESULT = new IntLiteral(e);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // factor ::= FLOAT 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.2: factor -> FLOAT");
    System.out.printf("REGLA 14.2: factor -> %s%n%n", e);
    RESULT = new FloatLiteral(e);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // factor ::= BOOLEAN 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.3: factor -> BOOLEAN");
    System.out.printf("REGLA 14.3: factor -> %s%n%n", e);
    RESULT = new BoolLiteral(e);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= ID 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
      System.out.println("REGLA 14.4: factor -> ID");
      if (!tablaSimbolos.exists(e)) {
                throw new RuntimeException("ERROR SEMÁNTICO: La variable '" + e + "' no ha sido declarada.");
            }
      String t = tablaSimbolos.getTipo(e);
      String tipoLLVM = "";

      if ("FLOAT_ARRAY".equals(t)) {
          tipoLLVM = tablaSimbolos.getTamano(e); //  Pasamos la dimensión ("10", "50", etc.) directamente
      } else {
          tipoLLVM = t;
      }

      RESULT = new IdLiteral(e, tipoLLVM);
  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= ID CORCH_A expr_arit CORCH_C 
            {
              Expresion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    System.out.println("REGLA 14.8: factor -> ARRAY[" + exp + "]");
    RESULT = new AccesoArray(i, exp, tablaSimbolos.getTamano(i));

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // factor ::= FLOAT_ARRAY 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.5: factor -> FLOAT_ARRAY");
    System.out.printf("REGLA 14.5: factor -> %s%n%n", e);
    RESULT = new ArrayLiteral(e);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // factor ::= READ_INT 
            {
              Expresion RESULT =null;
		
    System.out.println("REGLA 14.5: factor -> READ_INT()");
    RESULT = new ReadInt();

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // factor ::= READ_FLOAT 
            {
              Expresion RESULT =null;
		
    System.out.println("REGLA 14.5: factor -> READ_FLOAT()");
    RESULT = new ReadFloat();

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // factor ::= READ_BOOL 
            {
              Expresion RESULT =null;
		
    System.out.println("REGLA 14.5: factor -> READ_FLOAT()");
    RESULT = new ReadBoolean();

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // factor ::= PAREN_A expr_logica PAREN_C 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    System.out.println("REGLA 14.6: factor -> PAREN_A expresion PAREN_C");
    System.out.printf("REGLA 14.6: factor -> (%s)%n%n", e);
    RESULT = e;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // factor ::= VALOR_MAS_CERCANO PAREN_A expr_arit COMA FLOAT_ARRAY PAREN_C 
            {
              Expresion RESULT =null;
		int refleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int refright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Expresion ref = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int listaIdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaIdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String listaId = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    System.out.println("=== REGLA: Macro 'VALOR_MAS_CERCANO' (Usando solo Tabla Global) ===");

    // 0. ID únicos
    String sufijoUnico = String.valueOf(Math.abs(listaId.hashCode()));
    String nombreArreglo = "arr_literal_" + sufijoUnico;
    int dimension = listaId.replace("[", "").replace("]", "").split(",").length;
    String dimArreglo = String.valueOf(dimension);
    String varMasCercano = "_mc_masCercano_" + sufijoUnico;
    String varDistMin    = "_mc_distMin_"    + sufijoUnico;
    String varI          = "_mc_i_"          + sufijoUnico;
    String varDistActual = "_mc_distActual_" + sufijoUnico;

    // 1. Entorno Semántico (Solo Global)
    tablaSimbolos.add("ID", nombreArreglo, "FLOAT_ARRAY", dimArreglo, dimArreglo);
    tablaSimbolos.add("ID", varMasCercano, "FLOAT", "-", "-");
    tablaSimbolos.add("ID", varDistMin,    "FLOAT", "-", "-");
    tablaSimbolos.add("ID", varI,          "INT",   "-", "-");
    tablaSimbolos.add("ID", varDistActual, "FLOAT", "-", "-");

    // 2. Declaraciones
    ArrayList<String> varArreglo = new ArrayList<>();
    varArreglo.add(nombreArreglo);
    parser.declaracionesMacro.add(new DeclaracionArray(dimArreglo, varArreglo));

    ArrayList<String> varsFloat = new ArrayList<>();
    varsFloat.add(varMasCercano); varsFloat.add(varDistMin); varsFloat.add(varDistActual);
    parser.declaracionesMacro.add(new Declaracion("FLOAT", varsFloat));

    ArrayList<String> varsInt = new ArrayList<>();
    varsInt.add(varI);
    parser.declaracionesMacro.add(new Declaracion("INT", varsInt));

    ArrayList<Sentencia> pasos = new ArrayList<>();

    // 3. Poblado inicial
    String[] valoresArreglo = listaId.replace("[", "").replace("]", "").split(",");
    for (int k = 0; k < valoresArreglo.length; k++) {
        String elementoLimpio = valoresArreglo[k].trim();
        if (!elementoLimpio.isEmpty()) {
            pasos.add(new AsignacionArray(nombreArreglo, new IntLiteral(String.valueOf(k)), new FloatLiteral(elementoLimpio), dimArreglo));
        }
    }

    // 4. Lógica de conversión (🌟 Corregido el condicional duplicado)
    boolean needsConversion = "INT".equals(ref.getTipo());

    // 5. CONSTRUCCIÓN DEL SUBÁRBOL (🌟 Corregidos todos los new Asignacion)

    // 5.1. masCercano ← ARR[0]
    pasos.add(new Asignacion(varMasCercano,
        new AccesoArray(nombreArreglo, new IntLiteral("0"), dimArreglo),
        "FLOAT", "FLOAT"));

    // 5.2. IF ARR[0] - V >= 0
    pasos.add(new SentenciaIf(
        new Menor(
            new Resta(new AccesoArray(nombreArreglo, new IntLiteral("0"), dimArreglo), needsConversion ? new ConversionFloat(ref.copiar()) : ref.copiar(), "FLOAT"),
            new FloatLiteral("0.0"), "FLOAT"),
        new java.util.ArrayList<>(java.util.Arrays.asList(new Asignacion(varDistMin,
            new Resta(needsConversion ? new ConversionFloat(ref.copiar()) : ref.copiar(), new AccesoArray(nombreArreglo, new IntLiteral("0"), dimArreglo), "FLOAT"),
            "FLOAT", "FLOAT"))),
        new java.util.ArrayList<>(java.util.Arrays.asList(new Asignacion(varDistMin,
            new Resta(new AccesoArray(nombreArreglo, new IntLiteral("0"), dimArreglo), needsConversion ? new ConversionFloat(ref.copiar()) : ref.copiar(), "FLOAT"),
            "FLOAT", "FLOAT")))
    ));

    // 5.3. i ← 1
    pasos.add(new Asignacion(varI, new IntLiteral("1"), "INT", "INT"));

    // 5.4. CUERPO DEL BUCLE WHILE
    ArrayList<Sentencia> cuerpoWhile = new ArrayList<>();

    // IF ARR[i] - V >= 0
    cuerpoWhile.add(new SentenciaIf(
        new Menor(
            new Resta(new AccesoArray(nombreArreglo, new IdLiteral(varI, "INT"), dimArreglo), needsConversion ? new ConversionFloat(ref.copiar()) : ref.copiar(), "FLOAT"),
            new FloatLiteral("0.0"), "FLOAT"),
        new java.util.ArrayList<>(java.util.Arrays.asList(new Asignacion(varDistActual,
            new Resta(needsConversion ? new ConversionFloat(ref.copiar()) : ref.copiar(), new AccesoArray(nombreArreglo, new IdLiteral(varI, "INT"), dimArreglo), "FLOAT"),
            "FLOAT", "FLOAT"))),
        new java.util.ArrayList<>(java.util.Arrays.asList(new Asignacion(varDistActual,
            new Resta(new AccesoArray(nombreArreglo, new IdLiteral(varI, "INT"), dimArreglo), needsConversion ? new ConversionFloat(ref.copiar()) : ref.copiar(), "FLOAT"),
            "FLOAT", "FLOAT")))
    ));

    // IF dif < difMin
    cuerpoWhile.add(new SentenciaIf(
        new Menor(new IdLiteral(varDistActual, "FLOAT"), new IdLiteral(varDistMin, "FLOAT"), "FLOAT"),
        new java.util.ArrayList<>(java.util.Arrays.asList(
            new Asignacion(varDistMin, new IdLiteral(varDistActual, "FLOAT"), "FLOAT", "FLOAT"),
            new Asignacion(varMasCercano, new AccesoArray(nombreArreglo, new IdLiteral(varI, "INT"), dimArreglo), "FLOAT", "FLOAT")
        )),
        null
    ));

    // i ← i + 1
    cuerpoWhile.add(new Asignacion(varI, new Suma(new IdLiteral(varI, "INT"), new IntLiteral("1"), "INT"), "INT", "INT"));

    // 5.5. Control del While
    pasos.add(new SentenciaWhile(
        new Menor(new IdLiteral(varI, "INT"), new IntLiteral(dimArreglo), "INT"),
        cuerpoWhile, null));

    // Retorno final
    RESULT = new ValorMasCercano(needsConversion ? new ConversionFloat(ref.copiar()) : ref.copiar(), nombreArreglo, pasos, varMasCercano, listaId);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // factor ::= OP_RESTA factor 
            {
              Expresion RESULT =null;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion y = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    System.out.println("REGLA 14.7: factor -> - factor (unario)");
    System.out.printf("REGLA 14.7: factor -> -%s%n%n", y);
    RESULT = new MenosUnario(y, tablaSimbolos);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
