// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/lexer/lexico.flex

/****************************************************************************
 * En esta sección se puede incluir todo código que se copiará textualmente
 * al comienzo del archivo JAVA que contendrá la definición de la clase del 
 * analizador léxico.
 ****************************************************************************/
package lexer;
import java.util.ArrayList;

/****************************************************************************
 * Las siguientes directivas afectan el comportamiento del analizador léxico:
 *
 *  - %class Nombre --> Nombre de la clase generada.
 *  - %type Nombre  --> Tipo retornado por yylex().
 *  - %line         --> Número de línea (this.yyline)
 *  - %column       --> Número de columna (this.yycolumn)
 *
 * Existen otras directivas adicionales descriptas en la documentación.
 ****************************************************************************/

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int LINE_START = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\3\0\1\7\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\12\21\2\0\1\22\1\23"+
    "\1\24\2\0\1\25\5\26\1\27\5\26\1\30\1\26"+
    "\1\31\1\32\1\26\1\33\10\26\1\34\1\0\1\35"+
    "\1\0\1\36\1\0\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\26\1\50\1\51\1\26"+
    "\1\52\1\53\1\54\1\26\1\55\1\56\1\57\1\60"+
    "\1\26\1\61\1\26\1\62\1\26\1\63\1\64\1\65"+
    "\7\0\1\3\32\0\1\66\u01df\0\1\66\177\0\13\66"+
    "\35\0\2\3\5\0\1\66\57\0\1\66\240\0\1\66"+
    "\377\0\u0100\67";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\2\21\1\1\12\21\2\1\1\22\1\23"+
    "\2\24\1\25\1\26\1\0\1\27\1\30\1\0\1\31"+
    "\1\32\1\33\1\34\1\21\5\0\7\21\1\35\5\21"+
    "\2\0\1\36\1\37\2\0\1\21\2\0\15\21\2\0"+
    "\1\36\1\40\1\0\1\21\1\0\1\41\1\0\1\42"+
    "\4\21\1\43\1\44\4\21\1\45\1\21\2\0\1\46"+
    "\1\40\1\21\1\41\2\21\1\47\1\21\1\50\1\21"+
    "\1\51\1\21\1\52\1\0\2\46\11\21\1\46\1\53"+
    "\1\21\1\54\2\21\1\55\4\21\1\56\3\21\1\57"+
    "\1\60\1\21\1\61\2\21\1\62\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\160\0\340\0\u0118\0\u0150"+
    "\0\u0188\0\u01c0\0\160\0\160\0\160\0\160\0\160\0\u01f8"+
    "\0\160\0\u0230\0\u0268\0\u02a0\0\u02d8\0\u0310\0\u0348\0\u0380"+
    "\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0\0\u0508\0\u0540"+
    "\0\u0578\0\u05b0\0\u05e8\0\u0620\0\160\0\u0658\0\160\0\u0690"+
    "\0\u0658\0\160\0\u0150\0\160\0\160\0\u06c8\0\u01f8\0\160"+
    "\0\160\0\160\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818"+
    "\0\u0850\0\u0888\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u0310"+
    "\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0af0"+
    "\0\160\0\u0658\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78"+
    "\0\u0cb0\0\u0ce8\0\u0d20\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e38"+
    "\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50\0\u0b28\0\160\0\u0f88"+
    "\0\u0fc0\0\u0ff8\0\160\0\u1030\0\160\0\u1068\0\u10a0\0\u10d8"+
    "\0\u1110\0\u0310\0\u0310\0\u1148\0\u1180\0\u11b8\0\u11f0\0\u0310"+
    "\0\u1228\0\u1260\0\u1298\0\u0af0\0\u06c8\0\u12d0\0\u0770\0\u1308"+
    "\0\u1340\0\u0310\0\u1378\0\u13b0\0\u13e8\0\u0310\0\u1420\0\u0310"+
    "\0\u1458\0\160\0\u0b28\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570"+
    "\0\u15a8\0\u15e0\0\u1618\0\u1650\0\u0f18\0\u0310\0\u1688\0\u0310"+
    "\0\u16c0\0\u16f8\0\u0310\0\u1730\0\u1768\0\u17a0\0\u17d8\0\u0310"+
    "\0\u1810\0\u1848\0\u1880\0\u0310\0\u0310\0\u18b8\0\u0310\0\u18f0"+
    "\0\u1928\0\u0310\0\u0310";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\4\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\5\26\1\27\1\26"+
    "\1\30\2\3\1\31\1\32\1\33\1\26\1\34\1\35"+
    "\2\26\1\36\4\26\1\37\1\40\1\26\1\41\1\26"+
    "\1\42\1\26\1\43\1\44\3\3\1\45\1\46\1\47"+
    "\1\45\1\50\1\51\62\45\71\0\1\4\3\0\1\4"+
    "\64\0\1\5\110\0\1\52\44\0\2\53\1\54\2\0"+
    "\62\53\11\0\1\55\72\0\1\56\75\0\1\57\65\0"+
    "\1\57\1\0\1\22\71\0\1\60\67\0\1\61\67\0"+
    "\1\62\65\0\1\26\3\0\7\26\2\0\25\26\26\0"+
    "\1\26\3\0\6\26\1\63\2\0\25\26\6\0\5\64"+
    "\5\0\1\65\2\0\1\66\1\67\1\0\1\70\44\0"+
    "\1\64\22\0\1\26\3\0\7\26\2\0\13\26\1\71"+
    "\11\26\26\0\1\26\3\0\7\26\2\0\15\26\1\72"+
    "\1\26\1\73\5\26\26\0\1\26\3\0\7\26\2\0"+
    "\15\26\1\74\7\26\26\0\1\26\3\0\7\26\2\0"+
    "\13\26\1\75\11\26\26\0\1\26\3\0\7\26\2\0"+
    "\1\26\1\76\11\26\1\77\11\26\26\0\1\26\3\0"+
    "\7\26\2\0\6\26\1\100\5\26\1\101\10\26\26\0"+
    "\1\26\3\0\7\26\2\0\17\26\1\102\5\26\26\0"+
    "\1\26\3\0\7\26\2\0\5\26\1\103\17\26\26\0"+
    "\1\26\3\0\7\26\2\0\17\26\1\104\5\26\26\0"+
    "\1\26\3\0\7\26\2\0\10\26\1\105\14\26\5\0"+
    "\2\106\3\0\6\106\1\107\51\106\1\110\1\106\65\0"+
    "\1\111\4\0\1\112\1\47\1\0\1\50\1\112\64\0"+
    "\1\47\65\0\13\56\1\113\54\56\21\0\1\26\3\0"+
    "\4\26\1\114\2\26\2\0\25\26\6\0\5\64\10\0"+
    "\1\66\1\67\1\0\1\70\44\0\1\64\1\0\13\65"+
    "\1\115\54\65\17\0\1\67\1\0\1\70\67\0\1\116"+
    "\65\0\1\116\1\0\1\70\67\0\1\26\3\0\7\26"+
    "\2\0\21\26\1\117\3\26\26\0\1\26\3\0\7\26"+
    "\2\0\15\26\1\120\7\26\26\0\1\26\3\0\7\26"+
    "\2\0\5\26\1\121\17\26\26\0\1\26\3\0\7\26"+
    "\2\0\14\26\1\122\10\26\26\0\1\26\3\0\7\26"+
    "\2\0\11\26\1\123\6\26\1\124\4\26\26\0\1\26"+
    "\3\0\7\26\2\0\13\26\1\125\11\26\26\0\1\26"+
    "\3\0\7\26\2\0\15\26\1\126\7\26\26\0\1\26"+
    "\3\0\7\26\2\0\21\26\1\127\3\26\26\0\1\26"+
    "\3\0\7\26\2\0\11\26\1\130\13\26\26\0\1\26"+
    "\3\0\7\26\2\0\1\26\1\131\23\26\26\0\1\26"+
    "\3\0\7\26\2\0\22\26\1\132\2\26\26\0\1\26"+
    "\3\0\7\26\2\0\11\26\1\133\13\26\5\0\2\106"+
    "\3\0\60\106\1\110\1\106\1\0\2\107\3\134\6\107"+
    "\1\135\51\107\1\136\1\107\1\134\12\56\1\137\1\140"+
    "\54\56\21\0\1\26\3\0\2\26\1\141\4\26\2\0"+
    "\25\26\5\0\13\65\1\142\21\65\1\143\32\65\1\0"+
    "\5\144\7\0\1\64\3\0\1\116\13\0\1\145\30\0"+
    "\1\144\22\0\1\26\3\0\7\26\2\0\1\146\24\26"+
    "\26\0\1\26\3\0\7\26\2\0\13\26\1\147\11\26"+
    "\26\0\1\26\3\0\7\26\2\0\1\26\1\150\23\26"+
    "\26\0\1\26\3\0\7\26\2\0\21\26\1\151\3\26"+
    "\26\0\1\26\3\0\7\26\2\0\6\26\1\152\16\26"+
    "\26\0\1\26\3\0\7\26\2\0\5\26\1\153\17\26"+
    "\26\0\1\26\3\0\7\26\2\0\20\26\1\132\4\26"+
    "\26\0\1\26\3\0\7\26\2\0\1\26\1\154\23\26"+
    "\26\0\1\26\3\0\7\26\2\0\5\26\1\155\17\26"+
    "\26\0\1\26\3\0\7\26\2\0\14\26\1\156\10\26"+
    "\26\0\1\26\3\0\7\26\2\0\4\26\1\157\20\26"+
    "\26\0\1\26\3\0\7\26\2\0\5\26\1\160\17\26"+
    "\26\0\1\26\3\0\7\26\2\0\13\26\1\161\11\26"+
    "\5\0\13\134\1\162\54\134\2\107\3\134\6\107\1\163"+
    "\51\107\1\164\1\107\1\134\12\56\1\165\1\140\54\56"+
    "\21\0\1\26\3\0\6\26\1\166\2\0\25\26\5\0"+
    "\13\65\1\142\21\65\1\167\32\65\1\0\5\144\7\0"+
    "\1\64\17\0\1\145\30\0\1\144\22\0\1\26\3\0"+
    "\7\26\2\0\23\26\1\170\1\26\26\0\1\26\3\0"+
    "\7\26\2\0\5\26\1\171\17\26\26\0\1\26\3\0"+
    "\7\26\2\0\12\26\1\172\12\26\26\0\1\26\3\0"+
    "\7\26\2\0\11\26\1\173\13\26\26\0\1\26\3\0"+
    "\7\26\2\0\21\26\1\174\3\26\26\0\1\26\3\0"+
    "\7\26\2\0\7\26\1\175\15\26\26\0\1\26\3\0"+
    "\7\26\2\0\21\26\1\176\3\26\26\0\1\26\3\0"+
    "\7\26\2\0\1\177\24\26\26\0\1\26\3\0\7\26"+
    "\2\0\5\26\1\200\17\26\5\0\13\134\1\201\51\134"+
    "\1\202\2\134\2\107\3\134\6\107\1\163\51\107\1\203"+
    "\1\107\1\134\21\0\1\26\3\0\1\204\6\26\2\0"+
    "\25\26\26\0\1\26\3\0\7\26\2\0\10\26\1\205"+
    "\14\26\26\0\1\26\3\0\7\26\2\0\1\26\1\206"+
    "\23\26\26\0\1\26\3\0\7\26\2\0\14\26\1\207"+
    "\10\26\26\0\1\26\3\0\7\26\2\0\1\210\24\26"+
    "\26\0\1\26\3\0\7\26\2\0\5\26\1\211\17\26"+
    "\26\0\1\26\3\0\7\26\2\0\2\26\1\212\3\26"+
    "\1\213\2\26\1\214\13\26\5\0\13\134\1\201\51\134"+
    "\1\215\2\134\21\0\1\26\3\0\3\26\1\216\3\26"+
    "\2\0\25\26\26\0\1\26\3\0\7\26\2\0\11\26"+
    "\1\217\13\26\26\0\1\26\3\0\7\26\2\0\14\26"+
    "\1\220\10\26\26\0\1\26\3\0\7\26\2\0\22\26"+
    "\1\221\2\26\26\0\1\26\3\0\7\26\2\0\1\26"+
    "\1\222\23\26\26\0\1\26\3\0\7\26\2\0\17\26"+
    "\1\223\5\26\26\0\1\26\3\0\7\26\2\0\15\26"+
    "\1\224\7\26\26\0\1\26\3\0\7\26\2\0\13\26"+
    "\1\225\11\26\26\0\1\26\3\0\7\26\2\0\14\26"+
    "\1\226\10\26\26\0\1\26\3\0\7\26\2\0\13\26"+
    "\1\227\11\26\26\0\1\26\3\0\7\26\2\0\5\26"+
    "\1\230\17\26\26\0\1\26\3\0\7\26\2\0\17\26"+
    "\1\231\5\26\26\0\1\26\3\0\7\26\2\0\15\26"+
    "\1\232\7\26\26\0\1\26\3\0\7\26\2\0\15\26"+
    "\1\233\7\26\26\0\1\26\3\0\7\26\2\0\21\26"+
    "\1\234\3\26\26\0\1\26\3\0\7\26\2\0\5\26"+
    "\1\235\17\26\26\0\1\26\3\0\7\26\2\0\17\26"+
    "\1\236\5\26\26\0\1\26\3\0\7\26\2\0\13\26"+
    "\1\237\11\26\26\0\1\26\3\0\7\26\2\0\1\26"+
    "\1\240\23\26\26\0\1\26\3\0\7\26\2\0\1\26"+
    "\1\241\23\26\26\0\1\26\3\0\7\26\2\0\21\26"+
    "\1\242\3\26\26\0\1\26\3\0\7\26\2\0\24\26"+
    "\1\243\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6496];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\5\1\5\11\1\1\1\11"+
    "\23\1\1\11\1\1\1\11\2\1\1\11\1\0\2\11"+
    "\1\0\1\1\3\11\1\1\5\0\15\1\2\0\1\1"+
    "\1\11\2\0\1\1\2\0\15\1\2\0\1\1\1\11"+
    "\1\0\1\1\1\0\1\11\1\0\1\11\14\1\2\0"+
    "\15\1\1\0\1\11\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /* ─────────────────────────────────────────────────────────────────────
     * Variables de instancia
     * ───────────────────────────────────────────────────────────────────── */

    // ── Indentación significativa ────────────────────────────────────────
    /** Pila de niveles de indentación. El fondo siempre es 0. */
    java.util.Deque<Integer> indentStack = new java.util.ArrayDeque<>();

    /**
     * Cola de tokens generados pero aún no entregados al parser.
     * Se usa cuando una sola acción léxica produce más de un token
     */
    java.util.Queue<Token> pendingTokens = new java.util.LinkedList<>();

    /** Nivel de indentación acumulado mientras se escanea LINE_START. */
    int pendingIndent = 0;

    // Bloque de inicialización de instancia
    {
        indentStack.push(0);    // nivel base: columna 0
    }

    /* ─────────────────────────────────────────────────────────────────────
     * Métodos auxiliares para construir tokens
     * ───────────────────────────────────────────────────────────────────── */
    private Token token(String nombre) {
        return new Token(nombre, yyline, yycolumn);
    }

    private Token token(String nombre, Object valor) {
        return new Token(nombre, yyline, yycolumn, valor);
    }

    private Token token(String nombre, int line, int col, Object valor) {
        return new Token(nombre, line, col, valor);
    }

    /* ─────────────────────────────────────────────────────────────────────
     * processIndent(indent, line, col)
     *
     * Compara `indent` con el tope de la pila y produce los tokens
     * necesarios.  El primero se retorna; los adicionales van a
     * pendingTokens para ser entregados en llamadas posteriores.
     *
     *   indent > top  →  devuelve INDENT  (apila nuevo nivel)
     *   indent < top  →  devuelve DEDENT y encola N x DEDENT
     * ───────────────────────────────────────────────────────────────────── */
    private void processIndent(int indent, int line, int col) {
        int top = indentStack.peek();

        if (indent > top) {
            indentStack.push(indent);
            pendingTokens.add(new Token("INDENT", line, col));

        } else if (indent < top) {
            while (indentStack.peek() > indent) {
                indentStack.pop();
                pendingTokens.add(new Token("DEDENT", line, col));
            }

            // Verificar consistencia del nivel
            if (indentStack.peek() != indent) {
                throw new RuntimeException("Error: indentación inconsistente en línea " + line);
            }
        }
    }


    /* ─────────────────────────────────────────────────────────────────────
     * next_token() — requerido por java_cup.runtime.Scanner.
     * Sobrescribe el método generado por JFlex para manejar la cola de tokens
     *
     * Flujo:
     *   1. Si hay tokens pendientes, los entrega de a uno.
     *   2. Si no, llama a yylex().
     *   3. Si yylex() retorna null (EOF), cierra bloques con DEDENT y
     *      entrega el primero.
     *   4. Cuando la cola se vacía tras el EOF, retorna null: scan() de
     *      CUP lo convierte en END_OF_FILE.
     * ───────────────────────────────────────────────────────────────────── */
    public Token next_token() throws java.io.IOException {
        if (!pendingTokens.isEmpty()) {
            return pendingTokens.poll();
        }
        Token t = yylex();
        if (t == null) {
            processIndent(0, yyline, yycolumn);
            t = pendingTokens.isEmpty() ? null : pendingTokens.poll();
        }
        return t;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token("ERROR", "Error: carácter ilegal <" + yytext() + ">");
            }
            // fall through
          case 52: break;
          case 2:
            { /* ignorar */
            }
            // fall through
          case 53: break;
          case 3:
            { yybegin(LINE_START);
            }
            // fall through
          case 54: break;
          case 4:
            { return token("OP_NOT", yytext());
            }
            // fall through
          case 55: break;
          case 5:
            { return token("PARENTESIS_IZQ", yytext());
            }
            // fall through
          case 56: break;
          case 6:
            { return token("PARENTESIS_DER", yytext());
            }
            // fall through
          case 57: break;
          case 7:
            { return token("OP_MULTI", yytext());
            }
            // fall through
          case 58: break;
          case 8:
            { return token("OP_SUMA", yytext());
            }
            // fall through
          case 59: break;
          case 9:
            { return token("COMA", yytext());
            }
            // fall through
          case 60: break;
          case 10:
            { return token("OP_RESTA", yytext());
            }
            // fall through
          case 61: break;
          case 11:
            { return token("PUNTO", yytext());
            }
            // fall through
          case 62: break;
          case 12:
            { return token("OP_DIV",  yytext());
            }
            // fall through
          case 63: break;
          case 13:
            { return token("ENTERO", yytext());
            }
            // fall through
          case 64: break;
          case 14:
            { return token("OP_MENOR", yytext());
            }
            // fall through
          case 65: break;
          case 15:
            { return token("OP_ASIGNACION", yytext());
            }
            // fall through
          case 66: break;
          case 16:
            { return token("OP_MAYOR", yytext());
            }
            // fall through
          case 67: break;
          case 17:
            { return token("ID", yytext());
            }
            // fall through
          case 68: break;
          case 18:
            { yypushback(1);              // devolver el carácter para que sea leído por el YYINITIAL
                   yybegin(YYINITIAL);
                   processIndent(pendingIndent, yyline, yycolumn);
                   pendingIndent = 0;
                   if (!pendingTokens.isEmpty()) {
                       return pendingTokens.poll();
                   }
            }
            // fall through
          case 69: break;
          case 19:
            { pendingIndent +=  4;
            }
            // fall through
          case 70: break;
          case 20:
            { 
            }
            // fall through
          case 71: break;
          case 21:
            { pendingIndent++;
            }
            // fall through
          case 72: break;
          case 22:
            { return token("OP_DESIGUAL", yytext());
            }
            // fall through
          case 73: break;
          case 23:
            { return token("COMENTARIO_SIMPLE", yytext());
            }
            // fall through
          case 74: break;
          case 24:
            { return token("OP_AND", yytext());
            }
            // fall through
          case 75: break;
          case 25:
            { return token("FLOAT", yytext());
            }
            // fall through
          case 76: break;
          case 26:
            { return token("OP_MENORIGUAL", yytext());
            }
            // fall through
          case 77: break;
          case 27:
            { return token("OP_IGUAL", yytext());
            }
            // fall through
          case 78: break;
          case 28:
            { return token("OP_MAYORIGUAL", yytext());
            }
            // fall through
          case 79: break;
          case 29:
            { return token("IF", yytext());
            }
            // fall through
          case 80: break;
          case 30:
            { return token("COMENTARIO_SIMPLE_LLAVES", yytext());
            }
            // fall through
          case 81: break;
          case 31:
            { return token("OP_OR", yytext());
            }
            // fall through
          case 82: break;
          case 32:
            { return token("COMENTARIO_MULTILINEA_PARENTESIS", yytext());
            }
            // fall through
          case 83: break;
          case 33:
            { return token("COMENTARIO_MULTILINEA_CORCHETE", yytext());
            }
            // fall through
          case 84: break;
          case 34:
            { return token("FLOAT_ARRAY", yytext());
            }
            // fall through
          case 85: break;
          case 35:
            { return token("ELIF", yytext());
            }
            // fall through
          case 86: break;
          case 36:
            { return token("ELSE", yytext());
            }
            // fall through
          case 87: break;
          case 37:
            { return token("BOOLEAN", yytext());
            }
            // fall through
          case 88: break;
          case 38:
            { return token("COMENTARIO_MULTILINEA_LLAVES", yytext());
            }
            // fall through
          case 89: break;
          case 39:
            { return token("BREAK", yytext());
            }
            // fall through
          case 90: break;
          case 40:
            { return token("TIPO_FLOAT", yytext());
            }
            // fall through
          case 91: break;
          case 41:
            { return token("PRINT", yytext());
            }
            // fall through
          case 92: break;
          case 42:
            { return token("WHILE", yytext());
            }
            // fall through
          case 93: break;
          case 43:
            { return token("PROGRAM", yytext());
            }
            // fall through
          case 94: break;
          case 44:
            { return token("TIPO_BOOL", yytext());
            }
            // fall through
          case 95: break;
          case 45:
            { return token("TIPO_INT", yytext());
            }
            // fall through
          case 96: break;
          case 46:
            { return token("CONTINUE", yytext());
            }
            // fall through
          case 97: break;
          case 47:
            { return token("READ_INT", yytext());
            }
            // fall through
          case 98: break;
          case 48:
            { return token("ALT_WHILE", yytext());
            }
            // fall through
          case 99: break;
          case 49:
            { return token("READ_BOOL", yytext());
            }
            // fall through
          case 100: break;
          case 50:
            { return token("READ_FLOAT", yytext());
            }
            // fall through
          case 101: break;
          case 51:
            { return token("TIPO_ARRAY", yytext());
            }
            // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
