// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/lexer/lexico.flex

/****************************************************************************
 * En esta sección se puede incluir todo código que se copiará textualmente
 * al comienzo del archivo JAVA que contendrá la definición de la clase del 
 * analizador léxico.
 ****************************************************************************/
package lexer;
import java.util.ArrayList;

/****************************************************************************
 * Las siguientes directivas afectan el comportamiento del analizador léxico:
 *
 *  - %class Nombre --> Nombre de la clase generada.
 *  - %type Nombre  --> Tipo retornado por yylex().
 *  - %line         --> Número de línea (this.yyline)
 *  - %column       --> Número de columna (this.yycolumn)
 *
 * Existen otras directivas adicionales descriptas en la documentación.
 ****************************************************************************/

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int LINE_START = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\3\0\1\7\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\12\21\2\0\1\22\1\23"+
    "\1\24\2\0\1\25\1\26\1\27\1\30\1\31\1\26"+
    "\1\32\5\26\1\33\1\26\1\34\1\35\1\26\1\36"+
    "\10\26\1\37\1\0\1\40\1\0\1\41\1\0\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\26\1\53\1\54\1\26\1\55\1\56\1\57\1\26"+
    "\1\60\1\61\1\62\1\63\1\26\1\64\3\26\1\65"+
    "\1\66\1\67\7\0\1\3\32\0\1\70\u01df\0\1\70"+
    "\177\0\13\70\35\0\2\3\5\0\1\70\57\0\1\70"+
    "\240\0\1\70\377\0\u0100\71";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\1\1\12\1\13\1\14\1\15"+
    "\1\16\3\17\1\1\11\17\2\1\1\20\1\21\2\22"+
    "\1\23\1\0\1\24\1\25\1\0\1\26\1\27\1\30"+
    "\1\31\2\17\5\0\7\17\1\32\3\17\2\0\1\33"+
    "\1\34\2\0\2\17\2\0\6\17\1\35\4\17\2\0"+
    "\1\33\1\36\1\0\1\37\1\17\1\0\1\40\1\0"+
    "\1\41\1\0\3\17\1\42\1\43\1\17\1\44\1\17"+
    "\2\0\1\45\1\36\1\17\1\40\1\0\1\46\1\47"+
    "\1\17\1\50\1\51\1\0\2\45\1\17\1\0\1\17"+
    "\1\45\1\52\1\0\1\17\1\0\1\53\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\164\0\350\0\164\0\u0122"+
    "\0\u015c\0\u0196\0\164\0\164\0\164\0\164\0\u01d0\0\164"+
    "\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c\0\u0366\0\u03a0"+
    "\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc\0\u0536\0\u0570"+
    "\0\u05aa\0\u05e4\0\u061e\0\164\0\u0658\0\164\0\u0692\0\u0658"+
    "\0\u0122\0\164\0\164\0\u06cc\0\u01d0\0\164\0\164\0\164"+
    "\0\u0706\0\u0740\0\u077a\0\u07b4\0\u07ee\0\u0828\0\u0862\0\u089c"+
    "\0\u08d6\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8\0\u02f2\0\u0a32"+
    "\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0ae0\0\164\0\u0658\0\u0b54"+
    "\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea\0\u0d24"+
    "\0\u0d5e\0\u0d98\0\u02f2\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80\0\u0eba"+
    "\0\u0ef4\0\u0b1a\0\164\0\u0f2e\0\u02f2\0\u0f68\0\u0fa2\0\164"+
    "\0\u0fdc\0\164\0\u1016\0\u1050\0\u108a\0\u10c4\0\u02f2\0\u02f2"+
    "\0\u10fe\0\u02f2\0\u1138\0\u1172\0\u11ac\0\u0ae0\0\u06cc\0\u11e6"+
    "\0\u07b4\0\u1220\0\u02f2\0\u02f2\0\u125a\0\u02f2\0\u02f2\0\u1294"+
    "\0\164\0\u0b1a\0\u12ce\0\u1308\0\u1342\0\u0eba\0\u02f2\0\u137c"+
    "\0\u13b6\0\u13f0\0\u02f2\0\164";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\4\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\3\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\2\25\1\26\5\25"+
    "\1\27\1\25\1\30\2\3\1\31\1\32\1\33\1\25"+
    "\1\34\1\35\2\25\1\36\4\25\1\37\2\25\1\40"+
    "\1\25\1\41\1\42\1\43\3\3\1\44\1\45\1\46"+
    "\1\44\1\47\1\50\64\44\73\0\1\4\3\0\1\4"+
    "\66\0\1\5\67\0\2\51\1\52\2\0\64\51\11\0"+
    "\1\53\74\0\1\54\77\0\1\55\67\0\1\55\1\0"+
    "\1\21\73\0\1\56\71\0\1\57\71\0\1\60\67\0"+
    "\1\25\3\0\12\25\3\0\23\25\26\0\1\25\3\0"+
    "\7\25\1\61\2\25\3\0\23\25\26\0\1\25\3\0"+
    "\11\25\1\62\3\0\23\25\6\0\5\63\5\0\1\64"+
    "\2\0\1\65\1\66\1\0\1\67\46\0\1\63\22\0"+
    "\1\25\3\0\12\25\3\0\12\25\1\70\10\25\26\0"+
    "\1\25\3\0\12\25\3\0\4\25\1\71\11\25\1\72"+
    "\4\25\26\0\1\25\3\0\12\25\3\0\14\25\1\73"+
    "\6\25\26\0\1\25\3\0\12\25\3\0\12\25\1\74"+
    "\1\75\7\25\26\0\1\25\3\0\12\25\3\0\1\76"+
    "\22\25\26\0\1\25\3\0\12\25\3\0\5\25\1\77"+
    "\15\25\26\0\1\25\3\0\12\25\3\0\16\25\1\100"+
    "\4\25\26\0\1\25\3\0\12\25\3\0\16\25\1\101"+
    "\4\25\26\0\1\25\3\0\12\25\3\0\7\25\1\102"+
    "\13\25\5\0\2\103\3\0\6\103\1\104\53\103\1\105"+
    "\1\103\67\0\1\106\4\0\1\107\1\46\1\0\1\47"+
    "\1\107\66\0\1\46\67\0\13\54\1\110\56\54\21\0"+
    "\1\25\3\0\3\25\1\111\6\25\3\0\23\25\26\0"+
    "\1\25\3\0\7\25\1\112\2\25\3\0\23\25\6\0"+
    "\5\63\10\0\1\65\1\66\1\0\1\67\46\0\1\63"+
    "\1\0\13\64\1\113\56\64\17\0\1\66\1\0\1\67"+
    "\71\0\1\114\67\0\1\114\1\0\1\67\71\0\1\25"+
    "\3\0\12\25\3\0\20\25\1\115\2\25\26\0\1\25"+
    "\3\0\12\25\3\0\6\25\1\116\14\25\26\0\1\25"+
    "\3\0\12\25\3\0\4\25\1\117\16\25\26\0\1\25"+
    "\3\0\12\25\3\0\13\25\1\120\7\25\26\0\1\25"+
    "\3\0\12\25\3\0\10\25\1\121\6\25\1\122\3\25"+
    "\26\0\1\25\3\0\12\25\3\0\3\25\1\123\17\25"+
    "\26\0\1\25\3\0\12\25\3\0\12\25\1\124\10\25"+
    "\26\0\1\25\3\0\12\25\3\0\10\25\1\125\12\25"+
    "\26\0\1\25\3\0\12\25\3\0\21\25\1\126\1\25"+
    "\26\0\1\25\3\0\12\25\3\0\10\25\1\127\12\25"+
    "\5\0\2\103\3\0\62\103\1\105\1\103\1\0\2\104"+
    "\3\130\6\104\1\131\53\104\1\132\1\104\1\130\12\54"+
    "\1\133\1\134\56\54\21\0\1\25\3\0\4\25\1\135"+
    "\5\25\3\0\23\25\26\0\1\25\3\0\5\25\1\136"+
    "\4\25\3\0\23\25\5\0\13\64\1\137\24\64\1\140"+
    "\31\64\1\0\5\141\7\0\1\63\3\0\1\114\16\0"+
    "\1\142\27\0\1\141\22\0\1\25\3\0\12\25\2\0"+
    "\1\143\23\25\26\0\1\25\3\0\12\25\3\0\10\25"+
    "\1\144\12\25\26\0\1\25\3\0\12\25\3\0\1\145"+
    "\22\25\26\0\1\25\3\0\12\25\3\0\20\25\1\146"+
    "\2\25\26\0\1\25\3\0\12\25\3\0\5\25\1\147"+
    "\15\25\26\0\1\25\3\0\12\25\3\0\4\25\1\150"+
    "\16\25\26\0\1\25\3\0\12\25\3\0\17\25\1\126"+
    "\3\25\26\0\1\25\3\0\12\25\3\0\13\25\1\151"+
    "\7\25\26\0\1\25\3\0\12\25\3\0\4\25\1\152"+
    "\16\25\26\0\1\25\3\0\12\25\3\0\12\25\1\153"+
    "\10\25\5\0\13\130\1\154\56\130\2\104\3\130\6\104"+
    "\1\155\53\104\1\156\1\104\1\130\12\54\1\157\1\134"+
    "\56\54\21\0\1\25\3\0\11\25\1\160\3\0\23\25"+
    "\5\0\13\64\1\137\24\64\1\161\31\64\1\0\5\141"+
    "\7\0\1\63\22\0\1\142\27\0\1\141\65\0\1\162"+
    "\26\0\1\25\3\0\12\25\3\0\13\25\1\163\7\25"+
    "\26\0\1\25\3\0\12\25\3\0\11\25\1\164\11\25"+
    "\26\0\1\25\3\0\12\25\3\0\10\25\1\165\12\25"+
    "\26\0\1\25\3\0\12\25\3\0\20\25\1\166\2\25"+
    "\26\0\1\25\3\0\12\25\3\0\4\25\1\167\16\25"+
    "\5\0\13\130\1\170\53\130\1\171\2\130\2\104\3\130"+
    "\6\104\1\155\53\104\1\172\1\104\1\130\21\0\1\25"+
    "\3\0\1\173\11\25\3\0\23\25\56\0\1\174\41\0"+
    "\1\25\3\0\12\25\3\0\13\25\1\175\7\25\5\0"+
    "\13\130\1\170\53\130\1\176\2\130\21\0\1\25\3\0"+
    "\6\25\1\177\3\25\3\0\23\25\57\0\1\200\40\0"+
    "\1\25\3\0\12\25\3\0\21\25\1\201\1\25\61\0"+
    "\1\202\36\0\1\25\3\0\12\25\3\0\4\25\1\203"+
    "\16\25\53\0\1\204\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5162];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\1\1\1\11\3\1\4\11"+
    "\1\1\1\11\23\1\1\11\1\1\1\11\2\1\1\0"+
    "\2\11\1\0\1\1\3\11\2\1\5\0\13\1\2\0"+
    "\1\1\1\11\2\0\2\1\2\0\13\1\2\0\1\1"+
    "\1\11\1\0\2\1\1\0\1\11\1\0\1\11\1\0"+
    "\10\1\2\0\4\1\1\0\5\1\1\0\1\11\2\1"+
    "\1\0\3\1\1\0\1\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /* ─────────────────────────────────────────────────────────────────────
     * Variables de instancia
     * ───────────────────────────────────────────────────────────────────── */

    // ── Indentación significativa ────────────────────────────────────────
    /** Pila de niveles de indentación. El fondo siempre es 0. */
    java.util.Deque<Integer> indentStack = new java.util.ArrayDeque<>();

    /**
     * Cola de tokens generados pero aún no entregados al parser.
     * Se usa cuando una sola acción léxica produce más de un token
     */
    java.util.Queue<Token> pendingTokens = new java.util.LinkedList<>();

    /** Nivel de indentación acumulado mientras se escanea LINE_START. */
    int pendingIndent = 0;

    // Bloque de inicialización de instancia
    {
        indentStack.push(0);    // nivel base: columna 0
    }

    /* ─────────────────────────────────────────────────────────────────────
     * Métodos auxiliares para construir tokens
     * ───────────────────────────────────────────────────────────────────── */
    private Token token(String nombre) {
        return new Token(nombre, yyline, yycolumn);
    }

    private Token token(String nombre, Object valor) {
        return new Token(nombre, yyline, yycolumn, valor);
    }

    private Token token(String nombre, int line, int col, Object valor) {
        return new Token(nombre, line, col, valor);
    }

    /* ─────────────────────────────────────────────────────────────────────
     * processIndent(indent, line, col)
     *
     * Compara `indent` con el tope de la pila y produce los tokens
     * necesarios.  El primero se retorna; los adicionales van a
     * pendingTokens para ser entregados en llamadas posteriores.
     *
     *   indent > top  →  devuelve INDENT  (apila nuevo nivel)
     *   indent < top  →  devuelve DEDENT y encola N x DEDENT
     * ───────────────────────────────────────────────────────────────────── */
    private void processIndent(int indent, int line, int col) {
        int top = indentStack.peek();

        if (indent > top) {
            indentStack.push(indent);
            pendingTokens.add(new Token("INDENT", line, col));

        } else if (indent < top) {
            while (indentStack.peek() > indent) {
                indentStack.pop();
                pendingTokens.add(new Token("DEDENT", line, col));
            }

            // Verificar consistencia del nivel
            if (indentStack.peek() != indent) {
                throw new RuntimeException("Error: indentación inconsistente en línea " + line);
            }
        }
    }


    /* ─────────────────────────────────────────────────────────────────────
     * next_token() — requerido por java_cup.runtime.Scanner.
     * Sobrescribe el método generado por JFlex para manejar la cola de tokens
     *
     * Flujo:
     *   1. Si hay tokens pendientes, los entrega de a uno.
     *   2. Si no, llama a yylex().
     *   3. Si yylex() retorna null (EOF), cierra bloques con DEDENT y
     *      entrega el primero.
     *   4. Cuando la cola se vacía tras el EOF, retorna null: scan() de
     *      CUP lo convierte en END_OF_FILE.
     * ───────────────────────────────────────────────────────────────────── */
    public Token next_token() throws java.io.IOException {
        if (!pendingTokens.isEmpty()) {
            return pendingTokens.poll();
        }
        Token t = yylex();
        if (t == null) {
            processIndent(0, yyline, yycolumn);
            t = pendingTokens.isEmpty() ? null : pendingTokens.poll();
        }
        return t;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token("ERROR", "Error: carácter ilegal <" + yytext() + ">");
            }
            // fall through
          case 45: break;
          case 2:
            { /* ignorar */
            }
            // fall through
          case 46: break;
          case 3:
            { yybegin(LINE_START);
            }
            // fall through
          case 47: break;
          case 4:
            { return token("NOT", yytext());
            }
            // fall through
          case 48: break;
          case 5:
            { return token("PAREN_A", yytext());
            }
            // fall through
          case 49: break;
          case 6:
            { return token("PAREN_C", yytext());
            }
            // fall through
          case 50: break;
          case 7:
            { return token("OP_MULTI", yytext());
            }
            // fall through
          case 51: break;
          case 8:
            { return token("OP_SUMA", yytext());
            }
            // fall through
          case 52: break;
          case 9:
            { return token("OP_RESTA", yytext());
            }
            // fall through
          case 53: break;
          case 10:
            { return token("OP_DIV", yytext());
            }
            // fall through
          case 54: break;
          case 11:
            { return token("ENTERO", yytext());
            }
            // fall through
          case 55: break;
          case 12:
            { return token("MENOR", yytext());
            }
            // fall through
          case 56: break;
          case 13:
            { return token("IGUAL", yytext());
            }
            // fall through
          case 57: break;
          case 14:
            { return token("MAYOR", yytext());
            }
            // fall through
          case 58: break;
          case 15:
            { return token("ID", yytext());
            }
            // fall through
          case 59: break;
          case 16:
            { yypushback(1);              // devolver el carácter para que sea leído por el YYINITIAL
                   yybegin(YYINITIAL);
                   processIndent(pendingIndent, yyline, yycolumn);
                   pendingIndent = 0;
                   if (!pendingTokens.isEmpty()) {
                       return pendingTokens.poll();
                   }
            }
            // fall through
          case 60: break;
          case 17:
            { pendingIndent +=  4;
            }
            // fall through
          case 61: break;
          case 18:
            { 
            }
            // fall through
          case 62: break;
          case 19:
            { pendingIndent++;
            }
            // fall through
          case 63: break;
          case 20:
            { return token("COMENTARIO_SIMPLE", yytext());
            }
            // fall through
          case 64: break;
          case 21:
            { return token("OR", yytext());
            }
            // fall through
          case 65: break;
          case 22:
            { return token("FLOAT", yytext());
            }
            // fall through
          case 66: break;
          case 23:
            { return token("MENORIGUAL", yytext());
            }
            // fall through
          case 67: break;
          case 24:
            { return token("IGUALDAD", yytext());
            }
            // fall through
          case 68: break;
          case 25:
            { return token("MAYORIGUAL", yytext());
            }
            // fall through
          case 69: break;
          case 26:
            { return token("IF", yytext());
            }
            // fall through
          case 70: break;
          case 27:
            { return token("COMENTARIO_SIMPLE_LLAVES", yytext());
            }
            // fall through
          case 71: break;
          case 28:
            { return token("AND", yytext());
            }
            // fall through
          case 72: break;
          case 29:
            { return token("END", yytext());
            }
            // fall through
          case 73: break;
          case 30:
            { return token("COMENTARIO_MULTILINEA_PARENTESIS", yytext());
            }
            // fall through
          case 74: break;
          case 31:
            { return token("CODE",   yytext());
            }
            // fall through
          case 75: break;
          case 32:
            { return token("COMENTARIO_MULTILINEA_CORCHETE", yytext());
            }
            // fall through
          case 76: break;
          case 33:
            { return token("FLOAT_ARRAY", yytext());
            }
            // fall through
          case 77: break;
          case 34:
            { return token("ELIF", yytext());
            }
            // fall through
          case 78: break;
          case 35:
            { return token("ELSE", yytext());
            }
            // fall through
          case 79: break;
          case 36:
            { return token("BOOLEAN", yytext());
            }
            // fall through
          case 80: break;
          case 37:
            { return token("COMENTARIO_MULTILINEA_LLAVES", yytext());
            }
            // fall through
          case 81: break;
          case 38:
            { return token("BEGIN", yytext());
            }
            // fall through
          case 82: break;
          case 39:
            { return token("BREAK", yytext());
            }
            // fall through
          case 83: break;
          case 40:
            { return token("PRINT", yytext());
            }
            // fall through
          case 84: break;
          case 41:
            { return token("WHILE", yytext());
            }
            // fall through
          case 85: break;
          case 42:
            { return token("PROGRAM", yytext());
            }
            // fall through
          case 86: break;
          case 43:
            { return token("CONTINUE", yytext());
            }
            // fall through
          case 87: break;
          case 44:
            { return token("ALT_WHILE", yytext());
            }
            // fall through
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
