// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/lexer/lexico.flex

package lexer;
import java.util.ArrayList;

/****************************************************************************
 * Analizador léxico con manejo de estados para Strings y Comentarios.
 * Proyecto UNNOBA 2026.
 ****************************************************************************/


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int LINE_START = 2;
  public static final int STRING_STATE = 4;
  public static final int COMMENT_BRACE = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u1f00\1\u3500\1\u3600\1\u3700\1\u3800\1\u0100"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u1f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u1f00\1\u4c00\1\u4d00\1\u4e00"+
    "\1\u1f00\3\u0100\1\u4f00\1\u5000\1\u5100\12\u1f00\4\u0100\1\u5200"+
    "\17\u1f00\2\u0100\1\u5300\41\u1f00\2\u0100\1\u5400\1\u5500\2\u1f00"+
    "\1\u5600\1\u5700\27\u0100\1\u5800\2\u0100\1\u5900\45\u1f00\1\u0100"+
    "\1\u5a00\1\u5b00\11\u1f00\1\u5c00\27\u1f00\1\u5d00\1\u5e00\1\u5f00"+
    "\1\u6000\11\u1f00\1\u6100\1\u6200\5\u1f00\1\u6300\1\u6400\4\u1f00"+
    "\1\u6500\21\u1f00\246\u0100\1\u6600\20\u0100\1\u6700\1\u6800\25\u0100"+
    "\1\u6900\34\u0100\1\u6a00\14\u1f00\2\u0100\1\u6b00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\2\0\1\10\1\11\1\0\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\12\22\1\23\1\0"+
    "\1\24\1\25\1\26\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\31\1\36\2\31\1\37\1\40"+
    "\1\41\1\42\1\43\1\31\1\44\1\31\1\45\4\31"+
    "\1\46\1\31\1\47\1\50\1\51\1\0\1\52\1\0"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\31\1\64\1\65\1\66\1\67\1\70\1\71"+
    "\1\31\1\72\1\73\1\74\1\75\1\76\1\77\3\31"+
    "\1\100\1\101\1\102\7\0\1\3\32\0\1\3\11\0"+
    "\1\31\12\0\1\31\4\0\1\31\5\0\27\31\1\0"+
    "\37\31\1\0\u01ca\31\4\0\14\31\16\0\5\31\7\0"+
    "\1\31\1\0\1\31\201\0\5\31\1\0\2\31\2\0"+
    "\4\31\1\0\1\31\6\0\1\31\1\0\3\31\1\0"+
    "\1\31\1\0\24\31\1\0\123\31\1\0\213\31\10\0"+
    "\246\31\1\0\46\31\2\0\1\31\6\0\51\31\107\0"+
    "\33\31\4\0\4\31\55\0\53\31\43\0\2\31\1\0"+
    "\143\31\1\0\1\31\17\0\2\31\7\0\2\31\12\0"+
    "\3\31\2\0\1\31\20\0\1\31\1\0\36\31\35\0"+
    "\131\31\13\0\1\31\30\0\41\31\11\0\2\31\4\0"+
    "\1\31\5\0\26\31\4\0\1\31\11\0\1\31\3\0"+
    "\1\31\27\0\31\31\7\0\13\31\65\0\25\31\1\0"+
    "\10\31\106\0\66\31\3\0\1\31\22\0\1\31\7\0"+
    "\12\31\17\0\20\31\4\0\10\31\2\0\2\31\2\0"+
    "\26\31\1\0\7\31\1\0\1\31\3\0\4\31\3\0"+
    "\1\31\20\0\1\31\15\0\2\31\1\0\3\31\16\0"+
    "\2\31\12\0\1\31\10\0\6\31\4\0\2\31\2\0"+
    "\26\31\1\0\7\31\1\0\2\31\1\0\2\31\1\0"+
    "\2\31\37\0\4\31\1\0\1\31\23\0\3\31\20\0"+
    "\11\31\1\0\3\31\1\0\26\31\1\0\7\31\1\0"+
    "\2\31\1\0\5\31\3\0\1\31\22\0\1\31\17\0"+
    "\2\31\27\0\1\31\13\0\10\31\2\0\2\31\2\0"+
    "\26\31\1\0\7\31\1\0\2\31\1\0\5\31\3\0"+
    "\1\31\36\0\2\31\1\0\3\31\17\0\1\31\21\0"+
    "\1\31\1\0\6\31\3\0\3\31\1\0\4\31\3\0"+
    "\2\31\1\0\1\31\1\0\2\31\3\0\2\31\3\0"+
    "\3\31\3\0\14\31\26\0\1\31\64\0\10\31\1\0"+
    "\3\31\1\0\27\31\1\0\20\31\3\0\1\31\32\0"+
    "\3\31\5\0\2\31\36\0\1\31\4\0\10\31\1\0"+
    "\3\31\1\0\27\31\1\0\12\31\1\0\5\31\3\0"+
    "\1\31\40\0\1\31\1\0\2\31\17\0\2\31\22\0"+
    "\10\31\1\0\3\31\1\0\51\31\2\0\1\31\20\0"+
    "\1\31\5\0\3\31\10\0\3\31\30\0\6\31\5\0"+
    "\22\31\3\0\30\31\1\0\11\31\1\0\1\31\2\0"+
    "\7\31\72\0\60\31\1\0\2\31\14\0\7\31\72\0"+
    "\2\31\1\0\1\31\1\0\5\31\1\0\30\31\1\0"+
    "\1\31\1\0\12\31\1\0\2\31\11\0\1\31\2\0"+
    "\5\31\1\0\1\31\25\0\4\31\40\0\1\31\77\0"+
    "\10\31\1\0\44\31\33\0\5\31\163\0\53\31\24\0"+
    "\1\31\20\0\6\31\4\0\4\31\3\0\1\31\3\0"+
    "\2\31\7\0\3\31\4\0\15\31\14\0\1\31\21\0"+
    "\46\31\1\0\1\31\5\0\1\31\2\0\53\31\1\0"+
    "\115\31\1\0\4\31\2\0\7\31\1\0\1\31\1\0"+
    "\4\31\2\0\51\31\1\0\4\31\2\0\41\31\1\0"+
    "\4\31\2\0\7\31\1\0\1\31\1\0\4\31\2\0"+
    "\17\31\1\0\71\31\1\0\4\31\2\0\103\31\45\0"+
    "\20\31\20\0\126\31\2\0\6\31\3\0\u016c\31\2\0"+
    "\21\31\1\3\32\31\5\0\113\31\6\0\10\31\7\0"+
    "\15\31\1\0\4\31\16\0\22\31\16\0\22\31\16\0"+
    "\15\31\1\0\3\31\17\0\64\31\43\0\1\31\4\0"+
    "\1\31\103\0\131\31\7\0\5\31\2\0\42\31\1\0"+
    "\1\31\5\0\106\31\12\0\37\31\61\0\36\31\2\0"+
    "\5\31\13\0\54\31\4\0\32\31\66\0\27\31\11\0"+
    "\65\31\122\0\1\31\135\0\57\31\21\0\7\31\67\0"+
    "\36\31\15\0\2\31\12\0\54\31\32\0\44\31\51\0"+
    "\3\31\12\0\44\31\2\0\11\31\7\0\53\31\2\0"+
    "\3\31\51\0\4\31\1\0\6\31\1\0\2\31\3\0"+
    "\1\31\5\0\300\31\100\0\26\31\2\0\6\31\2\0"+
    "\46\31\2\0\6\31\2\0\10\31\1\0\1\31\1\0"+
    "\1\31\1\0\1\31\1\0\37\31\2\0\65\31\1\0"+
    "\7\31\1\0\1\31\3\0\3\31\1\0\7\31\3\0"+
    "\4\31\2\0\6\31\4\0\15\31\5\0\3\31\1\0"+
    "\7\31\3\0\13\3\35\0\2\3\5\0\1\3\57\0"+
    "\1\3\21\0\1\31\15\0\1\31\20\0\15\31\145\0"+
    "\1\31\4\0\1\31\2\0\12\31\1\0\1\31\3\0"+
    "\5\31\6\0\1\31\1\0\1\31\1\0\1\31\1\0"+
    "\4\31\1\0\13\31\2\0\4\31\5\0\5\31\4\0"+
    "\1\31\64\0\2\31\u017b\0\57\31\1\0\57\31\1\0"+
    "\205\31\6\0\4\31\3\0\2\31\14\0\46\31\1\0"+
    "\1\31\5\0\1\31\2\0\70\31\7\0\1\31\20\0"+
    "\27\31\11\0\7\31\1\0\7\31\1\0\7\31\1\0"+
    "\7\31\1\0\7\31\1\0\7\31\1\0\7\31\1\0"+
    "\7\31\120\0\1\31\320\0\1\3\4\0\2\31\52\0"+
    "\5\31\5\0\2\31\4\0\126\31\6\0\3\31\1\0"+
    "\132\31\1\0\4\31\5\0\53\31\1\0\136\31\21\0"+
    "\33\31\65\0\306\31\112\0\360\31\20\0\215\31\103\0"+
    "\56\31\2\0\15\31\3\0\20\31\12\0\2\31\24\0"+
    "\57\31\20\0\37\31\2\0\106\31\61\0\11\31\2\0"+
    "\147\31\2\0\65\31\2\0\5\31\60\0\13\31\1\0"+
    "\3\31\1\0\4\31\1\0\27\31\35\0\64\31\16\0"+
    "\62\31\76\0\6\31\3\0\1\31\1\0\2\31\13\0"+
    "\34\31\12\0\27\31\31\0\35\31\7\0\57\31\34\0"+
    "\1\31\20\0\5\31\1\0\12\31\12\0\5\31\1\0"+
    "\51\31\27\0\3\31\1\0\10\31\24\0\27\31\3\0"+
    "\1\31\3\0\62\31\1\0\1\31\3\0\2\31\2\0"+
    "\5\31\2\0\1\31\1\0\1\31\30\0\3\31\2\0"+
    "\13\31\7\0\3\31\14\0\6\31\2\0\6\31\2\0"+
    "\6\31\11\0\7\31\1\0\7\31\1\0\53\31\1\0"+
    "\14\31\10\0\163\31\35\0\244\31\14\0\27\31\4\0"+
    "\61\31\4\0\156\31\2\0\152\31\46\0\7\31\14\0"+
    "\5\31\5\0\1\31\1\0\12\31\1\0\15\31\1\0"+
    "\5\31\1\0\1\31\1\0\2\31\1\0\2\31\1\0"+
    "\154\31\41\0\153\31\22\0\100\31\2\0\66\31\50\0"+
    "\14\31\164\0\5\31\1\0\207\31\44\0\32\31\6\0"+
    "\32\31\13\0\131\31\3\0\6\31\2\0\6\31\2\0"+
    "\6\31\2\0\3\31\43\0\14\31\1\0\32\31\1\0"+
    "\23\31\1\0\2\31\1\0\17\31\2\0\16\31\42\0"+
    "\173\31\205\0\35\31\3\0\61\31\57\0\40\31\15\0"+
    "\24\31\1\0\10\31\6\0\46\31\12\0\36\31\2\0"+
    "\44\31\4\0\10\31\60\0\236\31\22\0\44\31\4\0"+
    "\44\31\4\0\50\31\10\0\64\31\234\0\67\31\11\0"+
    "\26\31\12\0\10\31\230\0\6\31\2\0\1\31\1\0"+
    "\54\31\1\0\2\31\3\0\1\31\2\0\27\31\12\0"+
    "\27\31\11\0\37\31\101\0\23\31\1\0\2\31\12\0"+
    "\26\31\12\0\32\31\106\0\70\31\6\0\2\31\100\0"+
    "\1\31\17\0\4\31\1\0\3\31\1\0\35\31\52\0"+
    "\35\31\3\0\35\31\43\0\10\31\1\0\34\31\33\0"+
    "\66\31\12\0\26\31\12\0\23\31\15\0\22\31\156\0"+
    "\111\31\67\0\63\31\15\0\63\31\15\0\44\31\334\0"+
    "\35\31\12\0\1\31\10\0\26\31\232\0\27\31\14\0"+
    "\65\31\113\0\55\31\40\0\31\31\32\0\44\31\35\0"+
    "\1\31\13\0\43\31\3\0\1\31\14\0\60\31\16\0"+
    "\4\31\25\0\1\31\1\0\1\31\43\0\22\31\1\0"+
    "\31\31\124\0\7\31\1\0\1\31\1\0\4\31\1\0"+
    "\17\31\1\0\12\31\7\0\57\31\46\0\10\31\2\0"+
    "\2\31\2\0\26\31\1\0\7\31\1\0\2\31\1\0"+
    "\5\31\3\0\1\31\22\0\1\31\14\0\5\31\236\0"+
    "\65\31\22\0\4\31\24\0\1\31\40\0\60\31\24\0"+
    "\2\31\1\0\1\31\270\0\57\31\51\0\4\31\44\0"+
    "\60\31\24\0\1\31\73\0\53\31\15\0\1\31\107\0"+
    "\33\31\345\0\54\31\164\0\100\31\37\0\1\31\240\0"+
    "\10\31\2\0\47\31\20\0\1\31\1\0\1\31\34\0"+
    "\1\31\12\0\50\31\7\0\1\31\25\0\1\31\13\0"+
    "\56\31\23\0\1\31\42\0\71\31\7\0\11\31\1\0"+
    "\45\31\21\0\1\31\61\0\36\31\160\0\7\31\1\0"+
    "\2\31\1\0\46\31\25\0\1\31\31\0\6\31\1\0"+
    "\2\31\1\0\40\31\16\0\1\31\u0147\0\23\31\15\0"+
    "\232\31\346\0\304\31\274\0\57\31\321\0\107\31\271\0"+
    "\71\31\7\0\37\31\161\0\36\31\22\0\60\31\20\0"+
    "\4\31\37\0\25\31\5\0\23\31\260\0\100\31\200\0"+
    "\113\31\5\0\1\31\102\0\15\31\100\0\2\31\1\0"+
    "\1\31\34\0\370\31\10\0\363\31\15\0\37\31\61\0"+
    "\3\31\21\0\4\31\10\0\u018c\31\4\0\153\31\5\0"+
    "\15\31\3\0\11\31\7\0\12\31\146\0\125\31\1\0"+
    "\107\31\1\0\2\31\2\0\1\31\2\0\2\31\2\0"+
    "\4\31\1\0\14\31\1\0\1\31\1\0\7\31\1\0"+
    "\101\31\1\0\4\31\2\0\10\31\1\0\7\31\1\0"+
    "\34\31\1\0\4\31\1\0\5\31\1\0\1\31\3\0"+
    "\7\31\1\0\u0154\31\2\0\31\31\1\0\31\31\1\0"+
    "\37\31\1\0\31\31\1\0\37\31\1\0\31\31\1\0"+
    "\37\31\1\0\31\31\1\0\37\31\1\0\31\31\1\0"+
    "\10\31\64\0\55\31\12\0\7\31\20\0\1\31\u0171\0"+
    "\54\31\24\0\305\31\73\0\104\31\7\0\1\31\264\0"+
    "\4\31\1\0\33\31\1\0\2\31\1\0\1\31\2\0"+
    "\1\31\1\0\12\31\1\0\4\31\1\0\1\31\1\0"+
    "\1\31\6\0\1\31\4\0\1\31\1\0\1\31\1\0"+
    "\1\31\1\0\3\31\1\0\2\31\1\0\1\31\2\0"+
    "\1\31\1\0\1\31\1\0\1\31\1\0\1\31\1\0"+
    "\1\31\1\0\2\31\1\0\1\31\2\0\4\31\1\0"+
    "\7\31\1\0\4\31\1\0\4\31\1\0\1\31\1\0"+
    "\12\31\1\0\21\31\5\0\3\31\1\0\5\31\1\0"+
    "\21\31\104\0\327\31\51\0\65\31\13\0\336\31\2\0"+
    "\u0182\31\16\0\u0131\31\37\0\36\31\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\2\3\1\4\1\5\1\2\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\1\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\7\22\1\23\1\24"+
    "\12\22\2\1\1\25\1\26\2\27\1\30\1\27\1\25"+
    "\1\31\1\32\1\31\2\33\1\34\1\35\1\36\1\37"+
    "\1\40\7\22\4\0\7\22\1\41\4\22\1\42\1\43"+
    "\1\0\1\44\1\45\1\46\1\47\1\50\1\51\2\22"+
    "\1\52\1\22\1\53\2\22\1\0\6\22\1\54\12\22"+
    "\1\0\1\55\4\22\1\56\1\57\1\22\1\60\2\22"+
    "\1\61\1\22\1\62\3\22\1\63\1\64\1\22\1\65"+
    "\1\22\1\66\10\22\1\67\1\70\12\22\1\71\3\22"+
    "\1\0\1\72\1\22\1\0\1\22\1\73\1\22\1\74"+
    "\1\0\1\22\1\75\5\22\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\206\0\311\0\u010c\0\u014f\0\u010c\0\u0192"+
    "\0\u010c\0\u010c\0\u01d5\0\u0218\0\u010c\0\u010c\0\u010c\0\u010c"+
    "\0\u010c\0\u010c\0\u025b\0\u010c\0\u029e\0\u010c\0\u02e1\0\u0324"+
    "\0\u0367\0\u03aa\0\u03ed\0\u0430\0\u0473\0\u04b6\0\u04f9\0\u053c"+
    "\0\u057f\0\u010c\0\u05c2\0\u0605\0\u0648\0\u068b\0\u06ce\0\u0711"+
    "\0\u0754\0\u0797\0\u07da\0\u081d\0\u0860\0\u08a3\0\u010c\0\u08e6"+
    "\0\u010c\0\u0929\0\u08e6\0\u096c\0\u09af\0\u010c\0\u010c\0\u09f2"+
    "\0\u010c\0\u0a35\0\u010c\0\u025b\0\u010c\0\u010c\0\u010c\0\u0a78"+
    "\0\u0abb\0\u0afe\0\u0b41\0\u0b84\0\u0bc7\0\u0c0a\0\u057f\0\u0c4d"+
    "\0\u0c90\0\u0cd3\0\u0d16\0\u0d59\0\u0d9c\0\u0ddf\0\u0e22\0\u0e65"+
    "\0\u0ea8\0\u0430\0\u0eeb\0\u0f2e\0\u0f71\0\u0fb4\0\u010c\0\u010c"+
    "\0\u08e6\0\u010c\0\u010c\0\u010c\0\u010c\0\u010c\0\u010c\0\u0ff7"+
    "\0\u103a\0\u0430\0\u107d\0\u0430\0\u10c0\0\u1103\0\u1146\0\u1189"+
    "\0\u11cc\0\u120f\0\u1252\0\u1295\0\u12d8\0\u0430\0\u131b\0\u135e"+
    "\0\u13a1\0\u13e4\0\u1427\0\u146a\0\u14ad\0\u14f0\0\u1533\0\u1576"+
    "\0\u15b9\0\u010c\0\u15fc\0\u163f\0\u1682\0\u16c5\0\u0430\0\u0430"+
    "\0\u1708\0\u0430\0\u174b\0\u178e\0\u0430\0\u17d1\0\u0430\0\u1814"+
    "\0\u1857\0\u189a\0\u0430\0\u0430\0\u18dd\0\u0430\0\u1920\0\u0430"+
    "\0\u1963\0\u19a6\0\u19e9\0\u1a2c\0\u1a6f\0\u1ab2\0\u1af5\0\u1b38"+
    "\0\u0430\0\u0430\0\u1b7b\0\u1bbe\0\u1c01\0\u1c44\0\u1c87\0\u1cca"+
    "\0\u1d0d\0\u1d50\0\u1d93\0\u1dd6\0\u0430\0\u1e19\0\u1e5c\0\u1e9f"+
    "\0\u1ee2\0\u0430\0\u1f25\0\u1f68\0\u1fab\0\u010c\0\u1fee\0\u010c"+
    "\0\u2031\0\u2074\0\u010c\0\u20b7\0\u20fa\0\u213d\0\u2180\0\u21c3"+
    "\0\u0430";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\5\1\10\1\6\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\3\34\1\35\1\34\1\36\4\34\1\37\1\40"+
    "\2\34\1\41\1\5\1\42\1\5\1\43\1\44\1\45"+
    "\1\34\1\46\1\47\2\34\1\50\5\34\1\51\2\34"+
    "\1\52\1\34\1\53\1\54\1\55\1\56\1\5\1\57"+
    "\1\60\1\61\1\57\1\62\1\63\2\57\1\64\67\57"+
    "\1\65\2\57\7\66\1\67\40\66\1\70\32\66\14\71"+
    "\1\72\66\71\104\0\1\6\3\0\1\6\77\0\1\7"+
    "\100\0\2\13\1\0\1\13\1\0\76\13\11\0\1\73"+
    "\113\0\1\74\100\0\1\74\1\0\1\25\105\0\1\75"+
    "\102\0\1\76\102\0\1\77\77\0\1\34\4\0\15\34"+
    "\1\100\2\34\3\0\26\34\25\0\1\34\4\0\13\34"+
    "\1\101\4\34\3\0\26\34\25\0\1\34\4\0\20\34"+
    "\3\0\26\34\25\0\1\34\4\0\7\34\1\102\1\103"+
    "\7\34\3\0\26\34\25\0\1\34\4\0\12\34\1\104"+
    "\5\34\3\0\26\34\25\0\1\34\4\0\15\34\1\105"+
    "\2\34\3\0\26\34\25\0\1\34\4\0\4\34\1\106"+
    "\13\34\3\0\26\34\4\0\5\107\11\0\1\110\1\111"+
    "\1\0\1\112\102\0\1\34\4\0\20\34\3\0\13\34"+
    "\1\113\12\34\25\0\1\34\4\0\20\34\3\0\5\34"+
    "\1\114\12\34\1\115\5\34\25\0\1\34\4\0\20\34"+
    "\3\0\16\34\1\116\7\34\25\0\1\34\4\0\20\34"+
    "\3\0\13\34\1\117\1\34\1\120\10\34\25\0\1\34"+
    "\4\0\20\34\3\0\1\34\1\121\24\34\25\0\1\34"+
    "\4\0\20\34\3\0\6\34\1\122\17\34\25\0\1\34"+
    "\4\0\20\34\3\0\20\34\1\123\5\34\25\0\1\34"+
    "\4\0\20\34\3\0\20\34\1\124\5\34\25\0\1\34"+
    "\4\0\20\34\3\0\1\34\1\125\24\34\25\0\1\34"+
    "\4\0\20\34\3\0\10\34\1\126\15\34\17\0\1\127"+
    "\167\0\1\130\2\0\1\131\1\61\1\0\1\62\1\131"+
    "\77\0\1\61\100\0\2\64\1\0\1\64\1\0\76\64"+
    "\14\0\1\132\75\0\1\133\40\0\1\134\16\0\1\135"+
    "\4\0\1\136\110\0\1\137\22\0\1\34\4\0\15\34"+
    "\1\140\2\34\3\0\26\34\25\0\1\34\4\0\13\34"+
    "\1\141\4\34\3\0\26\34\25\0\1\34\4\0\12\34"+
    "\1\142\5\34\3\0\26\34\25\0\1\34\4\0\13\34"+
    "\1\143\4\34\3\0\26\34\25\0\1\34\4\0\16\34"+
    "\1\144\1\34\3\0\26\34\25\0\1\34\4\0\13\34"+
    "\1\145\4\34\3\0\26\34\25\0\1\34\4\0\1\146"+
    "\17\34\3\0\26\34\23\0\1\111\1\0\1\112\102\0"+
    "\1\147\100\0\1\147\1\0\1\112\102\0\1\34\4\0"+
    "\20\34\3\0\22\34\1\150\3\34\25\0\1\34\4\0"+
    "\20\34\3\0\7\34\1\151\16\34\25\0\1\34\4\0"+
    "\20\34\3\0\5\34\1\152\20\34\25\0\1\34\4\0"+
    "\20\34\3\0\15\34\1\153\10\34\25\0\1\34\4\0"+
    "\20\34\3\0\11\34\1\154\7\34\1\155\4\34\25\0"+
    "\1\34\4\0\20\34\3\0\4\34\1\156\21\34\25\0"+
    "\1\34\4\0\20\34\3\0\13\34\1\157\12\34\25\0"+
    "\1\34\4\0\20\34\3\0\11\34\1\160\14\34\25\0"+
    "\1\34\4\0\20\34\3\0\23\34\1\161\2\34\25\0"+
    "\1\34\4\0\20\34\3\0\13\34\1\162\12\34\25\0"+
    "\1\34\4\0\20\34\3\0\11\34\1\163\14\34\25\0"+
    "\1\34\4\0\1\164\17\34\3\0\26\34\25\0\1\34"+
    "\4\0\10\34\1\165\7\34\3\0\26\34\25\0\1\34"+
    "\4\0\1\166\17\34\3\0\26\34\25\0\1\34\4\0"+
    "\6\34\1\167\11\34\3\0\26\34\25\0\1\34\4\0"+
    "\3\34\1\170\14\34\3\0\26\34\4\0\5\171\10\0"+
    "\1\107\3\0\1\147\26\0\1\172\53\0\1\34\4\0"+
    "\20\34\3\0\1\173\25\34\25\0\1\34\4\0\20\34"+
    "\3\0\11\34\1\174\14\34\25\0\1\34\4\0\20\34"+
    "\3\0\1\34\1\175\24\34\25\0\1\34\4\0\20\34"+
    "\3\0\22\34\1\176\3\34\25\0\1\34\4\0\20\34"+
    "\3\0\6\34\1\177\17\34\25\0\1\34\4\0\20\34"+
    "\3\0\5\34\1\200\20\34\25\0\1\34\4\0\20\34"+
    "\3\0\21\34\1\161\4\34\25\0\1\34\4\0\20\34"+
    "\3\0\15\34\1\201\10\34\25\0\1\34\4\0\20\34"+
    "\3\0\5\34\1\202\20\34\25\0\1\34\4\0\20\34"+
    "\3\0\16\34\1\203\7\34\25\0\1\34\4\0\20\34"+
    "\3\0\13\34\1\204\12\34\25\0\1\34\4\0\17\34"+
    "\1\205\3\0\26\34\25\0\1\34\4\0\4\34\1\206"+
    "\13\34\3\0\26\34\25\0\1\34\4\0\16\34\1\207"+
    "\1\34\3\0\26\34\25\0\1\34\4\0\15\34\1\210"+
    "\2\34\3\0\26\34\25\0\1\34\4\0\20\34\3\0"+
    "\1\211\25\34\4\0\5\171\10\0\1\107\32\0\1\172"+
    "\53\0\1\34\4\0\20\34\3\0\25\34\1\212\25\0"+
    "\1\34\4\0\20\34\3\0\15\34\1\213\10\34\25\0"+
    "\1\34\4\0\20\34\3\0\12\34\1\214\13\34\25\0"+
    "\1\34\4\0\20\34\3\0\11\34\1\215\14\34\25\0"+
    "\1\34\4\0\20\34\3\0\22\34\1\216\3\34\25\0"+
    "\1\34\4\0\20\34\3\0\20\34\1\217\5\34\25\0"+
    "\1\34\4\0\20\34\3\0\5\34\1\220\20\34\25\0"+
    "\1\34\4\0\1\221\17\34\3\0\26\34\25\0\1\34"+
    "\4\0\1\222\17\34\3\0\26\34\25\0\1\34\4\0"+
    "\1\34\1\223\3\34\1\224\1\34\1\225\10\34\3\0"+
    "\26\34\25\0\1\34\4\0\20\34\3\0\10\34\1\226"+
    "\15\34\25\0\1\34\4\0\20\34\3\0\15\34\1\227"+
    "\10\34\25\0\1\34\4\0\20\34\3\0\1\230\25\34"+
    "\25\0\1\34\4\0\12\34\1\231\5\34\3\0\26\34"+
    "\25\0\1\34\4\0\11\34\1\232\6\34\3\0\26\34"+
    "\25\0\1\34\4\0\13\34\1\233\4\34\3\0\26\34"+
    "\25\0\1\34\4\0\10\34\1\234\7\34\3\0\26\34"+
    "\25\0\1\34\4\0\12\34\1\235\5\34\3\0\26\34"+
    "\25\0\1\34\4\0\20\34\3\0\11\34\1\236\14\34"+
    "\25\0\1\34\4\0\20\34\3\0\23\34\1\237\2\34"+
    "\25\0\1\34\4\0\20\34\3\0\14\34\1\240\11\34"+
    "\25\0\1\34\4\0\13\34\1\241\4\34\3\0\26\34"+
    "\25\0\1\34\4\0\13\34\1\242\4\34\3\0\26\34"+
    "\25\0\1\34\4\0\16\34\1\243\1\34\3\0\26\34"+
    "\25\0\1\34\4\0\20\34\3\0\13\34\1\244\12\34"+
    "\25\0\1\34\4\0\20\34\3\0\5\34\1\245\20\34"+
    "\25\0\1\34\4\0\20\34\3\0\1\34\1\246\24\34"+
    "\25\0\1\34\4\0\10\34\1\247\7\34\3\0\26\34"+
    "\25\0\1\34\4\0\1\250\17\34\3\0\26\34\15\0"+
    "\1\251\7\0\1\34\4\0\20\34\3\0\26\34\25\0"+
    "\1\34\4\0\20\34\3\0\5\34\1\252\20\34\25\0"+
    "\1\34\4\0\20\34\3\0\21\34\1\253\4\34\15\0"+
    "\1\254\7\0\1\34\4\0\20\34\3\0\26\34\25\0"+
    "\1\34\4\0\16\34\1\255\1\34\3\0\26\34\16\0"+
    "\1\256\111\0\1\34\4\0\20\34\3\0\1\257\25\34"+
    "\16\0\1\260\101\0\1\261\7\0\1\34\4\0\20\34"+
    "\3\0\26\34\25\0\1\34\4\0\20\34\3\0\3\34"+
    "\1\262\22\34\16\0\1\263\111\0\1\34\4\0\20\34"+
    "\3\0\5\34\1\264\20\34\25\0\1\34\4\0\20\34"+
    "\3\0\20\34\1\265\5\34\25\0\1\34\4\0\20\34"+
    "\3\0\3\34\1\266\22\34\25\0\1\34\4\0\20\34"+
    "\3\0\1\34\1\267\24\34\25\0\1\34\4\0\20\34"+
    "\3\0\15\34\1\270\10\34\25\0\1\34\4\0\20\34"+
    "\3\0\16\34\1\271\7\34\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8710];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\1\1\1\11\1\1\2\11\2\1\6\11"+
    "\1\1\1\11\1\1\1\11\13\1\1\11\14\1\1\11"+
    "\1\1\1\11\4\1\2\11\1\1\1\11\1\1\1\11"+
    "\1\1\3\11\7\1\4\0\14\1\2\11\1\0\6\11"+
    "\7\1\1\0\21\1\1\0\1\11\56\1\1\0\2\1"+
    "\1\0\1\1\1\11\1\1\1\11\1\0\1\1\1\11"+
    "\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private StringBuilder stringBuffer = new StringBuilder();
    /* ─────────────────────────────────────────────────────────────────────
     * Variables de instancia
     * ───────────────────────────────────────────────────────────────────── */

    // ── Indentación significativa ────────────────────────────────────────
    /** Pila de niveles de indentación. El fondo siempre es 0. */
    java.util.Deque<Integer> indentStack = new java.util.ArrayDeque<>();

    /**
     * Cola de tokens generados pero aún no entregados al parser.
     * Se usa cuando una sola acción léxica produce más de un token
     */
    java.util.Queue<Token> pendingTokens = new java.util.LinkedList<>();

    /** Nivel de indentación acumulado mientras se escanea LINE_START. */
    int pendingIndent = 0;

    // Bloque de inicialización de instancia
    {
        indentStack.push(0);    // nivel base: columna 0
    }

    /* ─────────────────────────────────────────────────────────────────────
     * Métodos auxiliares para construir tokens
     * ───────────────────────────────────────────────────────────────────── */
    private Token token(String nombre) {
        return new Token(nombre, yyline, yycolumn);
    }

    private Token token(String nombre, Object valor) {
        return new Token(nombre, yyline, yycolumn, valor);
    }

    private Token token(String nombre, int line, int col, Object valor) {
        return new Token(nombre, line, col, valor);
    }

    /* ─────────────────────────────────────────────────────────────────────
     * processIndent(indent, line, col)
     *
     * Compara `indent` con el tope de la pila y produce los tokens
     * necesarios.  El primero se retorna; los adicionales van a
     * pendingTokens para ser entregados en llamadas posteriores.
     *
     *   indent > top  →  devuelve INDENT  (apila nuevo nivel)
     *   indent < top  →  devuelve DEDENT y encola N x DEDENT
     * ───────────────────────────────────────────────────────────────────── */
    private void processIndent(int indent, int line, int col) {
        int top = indentStack.peek();

        if (indent > top) {
            indentStack.push(indent);
            pendingTokens.add(new Token("INDENT", line, col));

        } else if (indent < top) {
            while (indentStack.peek() > indent) {
                indentStack.pop();
                pendingTokens.add(new Token("DEDENT", line, col));
            }

            // Verificar consistencia del nivel
            if (indentStack.peek() != indent) {
                throw new RuntimeException("Error: indentación inconsistente en línea " + line);
            }
        }
    }


    /* ─────────────────────────────────────────────────────────────────────
     * next_token() — requerido por java_cup.runtime.Scanner.
     * Sobrescribe el método generado por JFlex para manejar la cola de tokens
     *
     * Flujo:
     *   1. Si hay tokens pendientes, los entrega de a uno.
     *   2. Si no, llama a yylex().
     *   3. Si yylex() retorna null (EOF), cierra bloques con DEDENT y
     *      entrega el primero.
     *   4. Cuando la cola se vacía tras el EOF, retorna null: scan() de
     *      CUP lo convierte en END_OF_FILE.
     * ───────────────────────────────────────────────────────────────────── */
    public Token next_token() throws java.io.IOException {
        if (!pendingTokens.isEmpty()) {
            return pendingTokens.poll();
        }
        Token t = yylex();
        if (t == null) {
            processIndent(0, yyline, yycolumn);
            t = pendingTokens.isEmpty() ? null : pendingTokens.poll();
        }
        return t;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case STRING_STATE: {
              throw new RuntimeException("Error: Fin de archivo inesperado dentro de String");
            }  // fall though
            case 186: break;
            case COMMENT_BRACE: {
              throw new RuntimeException("Error: Comentario {* no cerrado");
            }  // fall though
            case 187: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token("ERROR", "Error: carácter ilegal <" + yytext() + ">");
            }
            // fall through
          case 63: break;
          case 2:
            { 
            }
            // fall through
          case 64: break;
          case 3:
            { yybegin(LINE_START);
            }
            // fall through
          case 65: break;
          case 4:
            { return token("NOT", yytext());
            }
            // fall through
          case 66: break;
          case 5:
            { stringBuffer = new StringBuilder();
        yybegin(STRING_STATE);
            }
            // fall through
          case 67: break;
          case 6:
            { return token("PAREN_A", yytext());
            }
            // fall through
          case 68: break;
          case 7:
            { return token("PAREN_C", yytext());
            }
            // fall through
          case 69: break;
          case 8:
            { return token("OP_MULTI", yytext());
            }
            // fall through
          case 70: break;
          case 9:
            { return token("OP_SUMA", yytext());
            }
            // fall through
          case 71: break;
          case 10:
            { return token("COMA", yytext());
            }
            // fall through
          case 72: break;
          case 11:
            { return token("OP_RESTA", yytext());
            }
            // fall through
          case 73: break;
          case 12:
            { return token("OP_DIV", yytext());
            }
            // fall through
          case 74: break;
          case 13:
            { return token("ENTERO", yytext());
            }
            // fall through
          case 75: break;
          case 14:
            { return token("DOS_PUNTOS", yytext());
            }
            // fall through
          case 76: break;
          case 15:
            { return token("MENOR", yytext());
            }
            // fall through
          case 77: break;
          case 16:
            { return token("IGUAL", yytext());
            }
            // fall through
          case 78: break;
          case 17:
            { return token("MAYOR", yytext());
            }
            // fall through
          case 79: break;
          case 18:
            { return token("ID", yytext());
            }
            // fall through
          case 80: break;
          case 19:
            { return token("CORCH_A", yytext());
            }
            // fall through
          case 81: break;
          case 20:
            { return token("CORCH_C", yytext());
            }
            // fall through
          case 82: break;
          case 21:
            { yypushback(1);
        yybegin(YYINITIAL);

        processIndent(pendingIndent, yyline, yycolumn);
        pendingIndent = 0;

        if (!pendingTokens.isEmpty())
            return pendingTokens.poll();
            }
            // fall through
          case 83: break;
          case 22:
            { pendingIndent += 4;
            }
            // fall through
          case 84: break;
          case 23:
            { pendingIndent = 0;
            }
            // fall through
          case 85: break;
          case 24:
            { pendingIndent++;
            }
            // fall through
          case 86: break;
          case 25:
            { stringBuffer.append(yytext());
            }
            // fall through
          case 87: break;
          case 26:
            { yybegin(YYINITIAL); return token("STRING", stringBuffer.toString());
            }
            // fall through
          case 88: break;
          case 27:
            { /* ignorar */
            }
            // fall through
          case 89: break;
          case 28:
            { return token("AND", yytext());
            }
            // fall through
          case 90: break;
          case 29:
            { return token("FLOAT", yytext());
            }
            // fall through
          case 91: break;
          case 30:
            { return token("MENORIGUAL", yytext());
            }
            // fall through
          case 92: break;
          case 31:
            { return token("IGUALDAD", yytext());
            }
            // fall through
          case 93: break;
          case 32:
            { return token("MAYORIGUAL", yytext());
            }
            // fall through
          case 94: break;
          case 33:
            { return token("IF", yytext());
            }
            // fall through
          case 95: break;
          case 34:
            { yybegin(COMMENT_BRACE);
            }
            // fall through
          case 96: break;
          case 35:
            { return token("OR", yytext());
            }
            // fall through
          case 97: break;
          case 36:
            { pendingIndent = 0;
        yybegin(COMMENT_BRACE);
            }
            // fall through
          case 98: break;
          case 37:
            { stringBuffer.append('\"');
            }
            // fall through
          case 99: break;
          case 38:
            { stringBuffer.append('\\');
            }
            // fall through
          case 100: break;
          case 39:
            { stringBuffer.append('\n');
            }
            // fall through
          case 101: break;
          case 40:
            { stringBuffer.append('\t');
            }
            // fall through
          case 102: break;
          case 41:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 103: break;
          case 42:
            { return token("FIN", yytext());
            }
            // fall through
          case 104: break;
          case 43:
            { return token("TYPE_INT", yytext());
            }
            // fall through
          case 105: break;
          case 44:
            { return token("END", yytext());
            }
            // fall through
          case 106: break;
          case 45:
            { return token("FLOAT_ARRAY", yytext());
            }
            // fall through
          case 107: break;
          case 46:
            { return token("ELIF", yytext());
            }
            // fall through
          case 108: break;
          case 47:
            { return token("ELSE", yytext());
            }
            // fall through
          case 109: break;
          case 48:
            { return token("BOOLEAN", yytext());
            }
            // fall through
          case 110: break;
          case 49:
            { return token("TYPE_ARRAY", yytext());
            }
            // fall through
          case 111: break;
          case 50:
            { return token("TYPE_FLOAT", yytext());
            }
            // fall through
          case 112: break;
          case 51:
            { return token("BEGIN", yytext());
            }
            // fall through
          case 113: break;
          case 52:
            { return token("BREAK", yytext());
            }
            // fall through
          case 114: break;
          case 53:
            { return token("PRINT", yytext());
            }
            // fall through
          case 115: break;
          case 54:
            { return token("WHILE", yytext());
            }
            // fall through
          case 116: break;
          case 55:
            { return token("TYPE_BOOL", yytext());
            }
            // fall through
          case 117: break;
          case 56:
            { return token("PROGRAM", yytext());
            }
            // fall through
          case 118: break;
          case 57:
            { return token("CONTINUE", yytext());
            }
            // fall through
          case 119: break;
          case 58:
            { return token("ALT_WHILE", yytext());
            }
            // fall through
          case 120: break;
          case 59:
            { return token("READ_INT", yytext());
            }
            // fall through
          case 121: break;
          case 60:
            { return token("READ_BOOL", yytext());
            }
            // fall through
          case 122: break;
          case 61:
            { return token("READ_FLOAT", yytext());
            }
            // fall through
          case 123: break;
          case 62:
            { return token("VALOR_MAS_CERCANO", yytext());
            }
            // fall through
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
